# Generated by Django 5.2.4 on 2025-11-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('peso_venda', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Peso Venda (DU_VB)')),
                ('peso_instalacao', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Peso Instalação (DU_GROSS)')),
                ('feriado', models.BooleanField(default=False, verbose_name='É Feriado?')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Obs')),
            ],
            options={
                'verbose_name': 'Dia Fiscal',
                'verbose_name_plural': 'Calendário Fiscal',
                'ordering': ['data'],
            },
        ),
    ]
