# Generated by Django 5.2.1 on 2025-12-28 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('contato', models.CharField(help_text='Somente números com DDD.', max_length=20, verbose_name='Contato (Zap/Tel)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Demanda')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor/Criador')),
            ],
            options={
                'verbose_name': 'CDOI',
                'verbose_name_plural': 'CDOIs',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Configuração Padrão', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('grupos_autorizados', models.ManyToManyField(help_text='Se quem cadastrou a demanda estiver em um destes grupos, o resumo será enviado para ele.', to='auth.group', verbose_name='Grupos Autorizados')),
            ],
            options={
                'verbose_name': 'Configuração de Envio',
                'verbose_name_plural': 'Configurações de Envio',
            },
        ),
    ]
