# Generated by Django 5.2.1 on 2025-12-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cdoi_configuracaoenvio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Aviso Backoffice - Novo CDOI', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('evento_gatilho', models.CharField(choices=[('NOVO_CDOI', 'Novo CDOI Solicitado (Record Vertical)')], default='NOVO_CDOI', max_length=50)),
                ('destinos_grupos', models.JSONField(blank=True, default=list, verbose_name='Grupos de Destino (IDs)')),
                ('destinos_numeros', models.JSONField(blank=True, default=list, verbose_name='Números Individuais')),
                ('template_mensagem', models.TextField(default='🔔 *NOVO CDOI*\nCliente: {cliente}\nResp: {usuario}', help_text='Variáveis disponíveis: {id}, {cliente}, {sindico}, {contato}, {total_hps}, {usuario}, {link}', verbose_name='Modelo da Mensagem')),
            ],
            options={
                'verbose_name': 'Regra de Automação',
                'verbose_name_plural': 'Regras de Automação',
            },
        ),
        migrations.RemoveField(
            model_name='configuracaoenvio',
            name='grupos_autorizados',
        ),
        migrations.DeleteModel(
            name='Cdoi',
        ),
        migrations.DeleteModel(
            name='ConfiguracaoEnvio',
        ),
    ]
