# Generated by Django 5.2.1 on 2026-09-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_regraautomacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraautomacao',
            name='evento_gatilho',
            field=models.CharField(choices=[('NOVO_CDOI', 'Novo CDOI Solicitado (Rosso Vertical)')], default='NOVO_CDOI', max_length=50),
        ),
    ]
