"""
Comando Django para criar a tabela usuarios_perfil se ela não existir
Uso: python manage.py criar_tabela_perfil
"""
from django.core.management.base import BaseCommand
from django.db import connection


class Command(BaseCommand):
    help = 'Cria a tabela usuarios_perfil se ela não existir (para correção após migração)'

    def handle(self, *args, **options):
        cursor = connection.cursor()
        
        try:
            # Verificar se a tabela existe
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'usuarios_perfil'
                );
            """)
            exists = cursor.fetchone()[0]
            
            if not exists:
                self.stdout.write(self.style.WARNING('Tabela usuarios_perfil nao existe. Criando...'))
                
                # Criar a tabela usuarios_perfil com TODOS os campos (incluindo cod_perfil)
                cursor.execute("""
                    CREATE TABLE "usuarios_perfil" (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "nome" varchar(100) NOT NULL UNIQUE,
                        "descricao" text NULL,
                        "cod_perfil" varchar(50) NOT NULL UNIQUE
                    );
                """)
                
                # Criar indices (usar IF NOT EXISTS para evitar erros)
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS "usuarios_perfil_nome_e44e3c8f_like" 
                    ON "usuarios_perfil" ("nome" varchar_pattern_ops);
                """)
                
                cursor.execute("""
                    CREATE INDEX IF NOT EXISTS "usuarios_perfil_cod_perfil_idx" 
                    ON "usuarios_perfil" ("cod_perfil");
                """)
                
                connection.commit()
                self.stdout.write(self.style.SUCCESS('Tabela usuarios_perfil criada com sucesso!'))
            else:
                self.stdout.write(self.style.SUCCESS('Tabela usuarios_perfil ja existe!'))
                
            # Verificar estrutura da tabela
            cursor.execute("""
                SELECT column_name, data_type, is_nullable 
                FROM information_schema.columns 
                WHERE table_name = 'usuarios_perfil' 
                ORDER BY ordinal_position;
            """)
            columns = cursor.fetchall()
            self.stdout.write('\nEstrutura da tabela usuarios_perfil:')
            for col in columns:
                self.stdout.write(f"  - {col[0]}: {col[1]} ({'NULL' if col[2] == 'YES' else 'NOT NULL'})")
                
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'ERRO: {e}'))
            connection.rollback()
            raise
