"""Lista canônica de municípios da oferta especial (UF, município)."""

CIDADES_OFERTA_ESPECIAL: list[tuple[str, str]] = [
    ('BA', 'EUNAPOLIS'),
    ('BA', 'FEIRA DE SANTANA'),
    ('BA', 'ILHEUS'),
    ('BA', 'ITABUNA'),
    ('BA', 'JEQUIE'),
    ('BA', 'JUAZEIRO'),
    ('BA', 'LAURO DE FREITAS'),
    ('BA', 'LUIS EDUARDO MAGALHAES'),
    ('BA', 'PAULO AFONSO'),
    ('BA', 'PORTO SEGURO'),
    ('BA', 'SIMOES FILHO'),
    ('BA', 'VITORIA DA CONQUISTA'),
    ('GO', 'CATALAO'),
    ('GO', 'FORMOSA'),
    ('GO', 'INHUMAS'),
    ('GO', 'LUZIANIA'),
    ('GO', 'MORRINHOS'),
    ('GO', 'NOVO GAMA'),
    ('GO', 'SENADOR CANEDO'),
    ('GO', 'VALPARAISO DE GOIAS'),
    ('TO', 'GURUPI'),
    ('TO', 'PARAISO DO TOCANTINS'),
    ('AL', 'ARAPIRACA'),
    ('AL', 'MACEIO'),
    ('AL', 'MARECHAL DEODORO'),
    ('CE', 'IGUATU'),
    ('CE', 'JUAZEIRO DO NORTE'),
    ('CE', 'MARACANAU'),
    ('CE', 'SOBRAL'),
    ('MA', 'PACO DO LUMIAR'),
    ('MA', 'SAO JOSE DE RIBAMAR'),
    ('MA', 'TIMON'),
    ('MS', 'MARACAJU'),
    ('MT', 'BARRA DO GARCAS'),
    ('MT', 'JUINA'),
    ('MT', 'PONTES E LACERDA'),
    ('MT', 'SINOP'),
    ('MT', 'TANGARA DA SERRA'),
    ('PB', 'CABEDELO'),
    ('PB', 'CAMPINA GRANDE'),
    ('PB', 'JOAO PESSOA'),
    ('PE', 'CABO DE SANTO AGOSTINHO'),
    ('PE', 'CARUARU'),
    ('PE', 'GOIANA'),
    ('PE', 'JABOATAO DOS GUARARAPES'),
    ('PE', 'PAULISTA'),
    ('PE', 'PETROLINA'),
    ('PI', 'FLORIANO'),
    ('PI', 'PARNAIBA'),
    ('PI', 'PIRIPIRI'),
    ('RN', 'MOSSORO'),
    ('RN', 'NATAL'),
    ('RO', 'CACOAL'),
    ('RO', 'JARU'),
    ('RO', 'OURO PRETO DO OESTE'),
    ('RO', 'PIMENTA BUENO'),
    ('RO', 'ROLIM DE MOURA'),
    ('SE', 'ITABAIANA'),
    ('MA', 'IMPERATRIZ'),
    ('PA', 'CASTANHAL'),
    ('PA', 'MARABA'),
    ('ES', 'CACHOEIRO DE ITAPEMIRIM'),
    ('RJ', 'CAMPOS DOS GOYTACAZES'),
    ('RJ', 'NOVA FRIBURGO'),
    ('RJ', 'RESENDE'),
    ('RJ', 'SAQUAREMA'),
    ('MG', 'ARAGUARI'),
    ('MG', 'CAXAMBU'),
    ('MG', 'CORONEL FABRICIANO'),
    ('MG', 'ESMERALDAS'),
    ('MG', 'GOVERNADOR VALADARES'),
    ('MG', 'IPATINGA'),
    ('MG', 'ITABIRA'),
    ('MG', 'JOAO MONLEVADE'),
    ('MG', 'LAVRAS'),
    ('MG', 'MURIAE'),
    ('MG', 'PARACATU'),
    ('MG', 'PATROCINIO'),
    ('MG', 'POCOS DE CALDAS'),
    ('MG', 'SABARA'),
    ('MG', 'SANTA RITA DO SAPUCAI'),
    ('MG', 'TIMOTEO'),
    ('RJ', 'PARACAMBI'),
    ('RJ', 'PIRAI'),
    ('SP', 'CAMPINAS'),
    ('SP', 'GUARULHOS'),
    ('SP', 'HORTOLANDIA'),
    ('SP', 'JUNDIAI'),
    ('SP', 'MOGI DAS CRUZES'),
    ('SP', 'SAO JOSE DOS CAMPOS'),
    ('SP', 'SOROCABA'),
    ('SP', 'VOTORANTIM'),
    ('PR', 'APUCARANA'),
    ('PR', 'ARAPONGAS'),
    ('PR', 'ASTORGA'),
    ('PR', 'CAMBE'),
    ('PR', 'CAMPINA GRANDE DO SUL'),
    ('PR', 'CAMPO LARGO'),
    ('PR', 'CAMPO MAGRO'),
    ('PR', 'CAMPO MOURAO'),
    ('PR', 'CASTRO'),
    ('PR', 'CIANORTE'),
    ('PR', 'COLORADO'),
    ('PR', 'CORNELIO PROCOPIO'),
    ('PR', 'FRANCISCO BELTRAO'),
    ('PR', 'GUARAPUAVA'),
    ('PR', 'GUARATUBA'),
    ('PR', 'IBIPORA'),
    ('PR', 'IRATI'),
    ('PR', 'JANDAIA DO SUL'),
    ('PR', 'LONDRINA'),
    ('PR', 'MARECHAL CANDIDO RONDON'),
    ('PR', 'MATINHOS'),
    ('PR', 'MEDIANEIRA'),
    ('PR', 'PALMAS'),
    ('PR', 'PATO BRANCO'),
    ('PR', 'QUATRO BARRAS'),
    ('PR', 'SANTO ANTONIO DA PLATINA'),
    ('PR', 'SAO PEDRO DO IVAI'),
    ('PR', 'SAO SEBASTIAO DA AMOREIRA'),
    ('PR', 'SARANDI'),
    ('PR', 'TOLEDO'),
    ('PR', 'UMUARAMA'),
    ('PR', 'UNIAO DA VITORIA'),
    ('RS', 'ALEGRETE'),
    ('RS', 'BAGE'),
    ('RS', 'BENTO GONCALVES'),
    ('RS', 'CAMAQUA'),
    ('RS', 'CAMPO BOM'),
    ('RS', 'CARAZINHO'),
    ('RS', 'ELDORADO DO SUL'),
    ('RS', 'ERECHIM'),
    ('RS', 'ESTANCIA VELHA'),
    ('RS', 'FARROUPILHA'),
    ('RS', 'FLORES DA CUNHA'),
    ('RS', 'GARIBALDI'),
    ('RS', 'IJUI'),
    ('RS', 'LAJEADO'),
    ('RS', 'MARAU'),
    ('RS', 'MONTENEGRO'),
    ('RS', 'RIO GRANDE'),
    ('RS', 'RIO PARDO'),
    ('RS', 'TAQUARA'),
    ('RS', 'URUGUAIANA'),
    ('SC', 'BALNEARIO CAMBORIU'),
    ('SC', 'CHAPECO'),
    ('SC', 'CRICIUMA'),
    ('SC', 'GAROPABA'),
    ('SC', 'GUABIRUBA'),
    ('SC', 'ICARA'),
    ('SC', 'INDAIAL'),
    ('SC', 'ITUPORANGA'),
    ('SC', 'RIO DO SUL'),
    ('SC', 'SAO JOSE'),
    ('RS', 'ROSARIO DO SUL'),
    ('RS', 'SANTIAGO'),
    ('RS', 'VENANCIO AIRES'),
    ('GO', 'TRINDADE'),
    ('SC', 'PALHOCA'),
    ('PR', 'FOZ DO IGUACU'),
    ('MG', 'MONTES CLAROS'),
]

# Valor acordado na tabela '600MB CIDADE ESPECIAL'
VALOR_COMISSAO_600MB_CIDADE_ESPECIAL = '105.00'
