# Generated by Django 5.2.1 on 2026-01-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', 'add_venda_reemissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfv',
            name='nome_cdo',
            field=models.CharField(blank=True, help_text='Nome do CDO', max_length=100, null=True),
        ),
    ]
