# Generated by Django 5.2.4 on 2025-08-31 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venda', models.CharField(choices=[('PAP', 'PAP'), ('TELAG', 'TELAG')], max_length=10)),
                ('tipo_cliente', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=10)),
                ('valor_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_acelerado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao', to='crm_app.plano')),
            ],
            options={
                'verbose_name': 'Regra de Comissão',
                'verbose_name_plural': 'Regras de Comissão',
                'unique_together': {('consultor', 'plano', 'tipo_venda', 'tipo_cliente')},
            },
        ),
    ]
