# Generated by Django 5.2.1 on 2025-09-05 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_regracomissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
                ('nome_razao_social', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nome_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_residencia', models.CharField(max_length=20, verbose_name='Número (Fachada)')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('valor_comissao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Comissão')),
                ('comissao_calculada', models.BooleanField(default=False, verbose_name='Comissão Calculada?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='crm_app.cliente', verbose_name='Cliente')),
                ('dono_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL, verbose_name='Dono da Venda (Vendedor)')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_app.formapagamento', verbose_name='Forma de Pagamento')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_app.plano', verbose_name='Plano')),
                ('regra_comissao_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm_app.regracomissao', verbose_name='Regra de Comissão Aplicada')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm_app.statuscrm', verbose_name='Status da Venda')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'venda',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
