# Generated by Django 5.2.1 on 2025-09-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_cliente_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cpf_representante_legal',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Representante Legal'),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_entrada',
            field=models.CharField(choices=[('APP', 'VENDA NO APP'), ('SEM_APP', 'VENDA SEM APP')], max_length=10, null=True, verbose_name='Forma de Entrada'),
        ),
        migrations.AddField(
            model_name='venda',
            name='telefone1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1'),
        ),
        migrations.AddField(
            model_name='venda',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2'),
        ),
    ]
