# Generated by Django 5.2.1 on 2025-09-06 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_cliente_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='motivopendencia',
            options={'verbose_name': 'Motivo de Pendência', 'verbose_name_plural': 'Motivos de Pendência'},
        ),
        migrations.AlterModelOptions(
            name='operadora',
            options={'verbose_name': 'Operadora', 'verbose_name_plural': 'Operadoras'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterModelOptions(
            name='statuscrm',
            options={'verbose_name': 'Status de CRM', 'verbose_name_plural': 'Status de CRM'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.RenameField(
            model_name='formapagamento',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='operadora',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='status',
            new_name='ativo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='comissao_calculada',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='regra_comissao_aplicada',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='valor_comissao',
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='aplica_desconto',
            field=models.BooleanField(default=False, help_text='Marque esta opção se esta forma de pagamento aplica o desconto de R$10,00 nos planos.'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_razao_social',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='motivopendencia',
            name='tipo_pendencia',
            field=models.CharField(help_text='Ex: Documentação, Financeiro, Técnico', max_length=100),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operadora',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='regracomissao',
            name='tipo_cliente',
            field=models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], max_length=4),
        ),
        migrations.AlterField(
            model_name='regracomissao',
            name='tipo_venda',
            field=models.CharField(choices=[('PAP', 'PAP'), ('TELAG', 'TELAG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='statuscrm',
            name='estado',
            field=models.CharField(blank=True, help_text='Ex: Pendente, Em Andamento, Finalizado, Cancelado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='statuscrm',
            name='tipo',
            field=models.CharField(choices=[('Tratamento', 'Tratamento'), ('Esteira', 'Esteira'), ('Comissionamento', 'Comissionamento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='crm_app.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cpf_representante_legal',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='dono_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_entrada',
            field=models.CharField(choices=[('APP', 'APP'), ('SEM_APP', 'SEM_APP')], default='APP', max_length=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_app.formapagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero_residencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_app.plano'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.statuscrm'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='telefone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='telefone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='statuscrm',
            unique_together={('nome', 'tipo')},
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='crm_cliente',
        ),
        migrations.AlterModelTable(
            name='formapagamento',
            table='crm_forma_pagamento',
        ),
        migrations.AlterModelTable(
            name='motivopendencia',
            table='crm_motivo_pendencia',
        ),
        migrations.AlterModelTable(
            name='operadora',
            table='crm_operadora',
        ),
        migrations.AlterModelTable(
            name='plano',
            table='crm_plano',
        ),
        migrations.AlterModelTable(
            name='regracomissao',
            table='crm_regra_comissao',
        ),
        migrations.AlterModelTable(
            name='statuscrm',
            table='crm_status',
        ),
        migrations.AlterModelTable(
            name='venda',
            table='crm_venda',
        ),
    ]
