# Generated by Django 5.2.4 on 2025-09-07 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_alter_cliente_options_alter_formapagamento_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='dono_venda',
            new_name='vendedor',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='status',
        ),
        migrations.AddField(
            model_name='venda',
            name='status_esteira',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'Esteira'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_esteira', to='crm_app.statuscrm'),
        ),
        migrations.AddField(
            model_name='venda',
            name='status_tratamento',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'Tratamento'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_tratamento', to='crm_app.statuscrm'),
        ),
    ]
