# Generated by Django 5.2.4 on 2025-09-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_rename_dono_venda_venda_vendedor_remove_venda_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Agendamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_pedido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Pedido'),
        ),
        migrations.AddField(
            model_name='venda',
            name='ordem_servico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ordem de Serviço (O.S)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='periodo_agendamento',
            field=models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde')], max_length=10, null=True, verbose_name='Período'),
        ),
    ]
