# Generated by Django 5.2.4 on 2025-09-08 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_venda_data_agendamento_venda_data_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status_comissionamento',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'Comissionamento'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_comissionamento', to='crm_app.statuscrm'),
        ),
    ]
