# Generated by Django 5.2.4 on 2025-09-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_venda_status_comissionamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoOsab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('produto', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula_vendedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula do Vendedor')),
                ('gv', models.CharField(blank=True, max_length=255, null=True)),
                ('sap_principal_fim', models.CharField(blank=True, max_length=255, null=True)),
                ('gestao', models.CharField(blank=True, max_length=255, null=True)),
                ('st_regional', models.CharField(blank=True, max_length=255, null=True)),
                ('gc', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_pedido', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número do Pedido')),
                ('dt_gross', models.DateField(blank=True, null=True, verbose_name='Data Gross')),
                ('anomes_gross', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ano/Mês Gross')),
                ('dt_retirada', models.DateField(blank=True, null=True, verbose_name='Data Retirada')),
                ('anomes_retirada', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ano/Mês Retirada')),
                ('grupo_unidade', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_retirada', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_retirada', models.CharField(blank=True, max_length=255, null=True)),
                ('submotivo_retirada', models.CharField(blank=True, max_length=255, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_apelido', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Importação OSAB',
                'verbose_name_plural': 'Importações OSAB',
                'db_table': 'crm_importacao_osab',
            },
        ),
    ]
