# Generated by Django 5.2.4 on 2025-09-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_importacaoosab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoChurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('produto', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula_vendedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula do Vendedor')),
                ('gv', models.CharField(blank=True, max_length=255, null=True)),
                ('sap_principal_fim', models.CharField(blank=True, max_length=255, null=True)),
                ('gestao', models.CharField(blank=True, max_length=255, null=True)),
                ('st_regional', models.CharField(blank=True, max_length=255, null=True)),
                ('gc', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_pedido', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número do Pedido')),
                ('dt_gross', models.DateField(blank=True, null=True, verbose_name='Data Gross')),
                ('anomes_gross', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ano/Mês Gross')),
                ('dt_retirada', models.DateField(blank=True, null=True, verbose_name='Data Retirada')),
                ('anomes_retirada', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ano/Mês Retirada')),
                ('grupo_unidade', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_retirada', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_retirada', models.CharField(blank=True, max_length=255, null=True)),
                ('submotivo_retirada', models.CharField(blank=True, max_length=255, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_apelido', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Importação Churn',
                'verbose_name_plural': 'Importações Churn',
                'db_table': 'crm_importacao_churn',
            },
        ),
        migrations.RenameField(
            model_name='importacaoosab',
            old_name='classificacao',
            new_name='classe_produto',
        ),
        migrations.RenameField(
            model_name='importacaoosab',
            old_name='desc_apelido',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='importacaoosab',
            old_name='grupo_unidade',
            new_name='cluster',
        ),
        migrations.RenameField(
            model_name='importacaoosab',
            old_name='motivo_retirada',
            new_name='cod_pendencia',
        ),
        migrations.RenameField(
            model_name='importacaoosab',
            old_name='municipio',
            new_name='comunidade',
        ),
        migrations.RenameField(
            model_name='importacaoosab',
            old_name='submotivo_retirada',
            new_name='contato1',
        ),
        migrations.RenameField(
            model_name='importacaoosab',
            old_name='tipo_retirada',
            new_name='contato2',
        ),
        migrations.RemoveField(
            model_name='importacaoosab',
            name='anomes_gross',
        ),
        migrations.RemoveField(
            model_name='importacaoosab',
            name='anomes_retirada',
        ),
        migrations.RemoveField(
            model_name='importacaoosab',
            name='codigo_sap',
        ),
        migrations.RemoveField(
            model_name='importacaoosab',
            name='dt_gross',
        ),
        migrations.RemoveField(
            model_name='importacaoosab',
            name='dt_retirada',
        ),
        migrations.RemoveField(
            model_name='importacaoosab',
            name='numero_pedido',
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='contato3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='dacc_efe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='dacc_sol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='data_abertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='desc_pendencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='dia_vencimento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='documento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='dt_ref',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='duplicidade_vl_planta_mesmo_endereco_cpf_diferente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='duplicidade_vl_planta_mesmo_endereco_cpf_igual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='duplicidade_vl_vl_mesmo_endereco_cpf_diferente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='duplicidade_vl_vl_mesmo_endereco_cpf_igual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='estacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='filial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='flag_vll',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='flg_mig_cobre_fixo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='flg_mig_cobre_velox',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='flg_mig_tv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='id_bundle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='localidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='meio_pagamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='nome_canal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='numero_ba',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='oferta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='pdv_sap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='safra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='segmento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='situacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='status_checkout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='tipo_pendencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='velocidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='venda_no_app',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
