# Generated by Django 5.2.4 on 2025-09-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0011_importacaochurn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloPagamento',
            fields=[
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.CharField(blank=True, max_length=20, null=True)),
                ('quinzena', models.CharField(blank=True, max_length=10, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=50, null=True)),
                ('ciclo_complementar', models.CharField(blank=True, max_length=50, null=True)),
                ('evento', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('canal_detalhado', models.CharField(blank=True, max_length=100, null=True)),
                ('canal_agrupado', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_canal', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_sap_agr', models.CharField(blank=True, max_length=50, null=True)),
                ('parceiro_agr', models.CharField(blank=True, max_length=255, null=True)),
                ('uf_parceiro_agr', models.CharField(blank=True, max_length=2, null=True)),
                ('familia', models.CharField(blank=True, max_length=100, null=True)),
                ('produto', models.CharField(blank=True, max_length=100, null=True)),
                ('oferta', models.CharField(blank=True, max_length=255, null=True)),
                ('plano_detalhado', models.CharField(blank=True, max_length=255, null=True)),
                ('celula', models.CharField(blank=True, max_length=100, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('contrato', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('num_os_pedido_siebel', models.CharField(blank=True, max_length=50, null=True)),
                ('id_bundle', models.CharField(blank=True, max_length=50, null=True)),
                ('data_atv', models.DateField(blank=True, null=True)),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('qtd', models.IntegerField(blank=True, null=True)),
                ('comissao_bruta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fator', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iq', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_comissao_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ciclo de Pagamento',
                'verbose_name_plural': 'Ciclos de Pagamento',
                'db_table': 'crm_ciclo_pagamento',
            },
        ),
    ]
