# Generated by Django 5.2.4 on 2025-09-11 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_ciclopagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAlteracaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('alteracoes', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_vendas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='crm_app.venda')),
            ],
            options={
                'verbose_name': 'Histórico de Alteração de Venda',
                'verbose_name_plural': 'Históricos de Alteração de Venda',
                'db_table': 'crm_historico_alteracao_venda',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
