# Generated by Django 5.2.1 on 2025-09-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_historicoalteracaovenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='venda',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência'),
        ),
    ]
