# Generated by Django 5.2.4 on 2025-09-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_venda_observacoes_venda_ponto_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago'),
        ),
        migrations.AlterField(
            model_name='statuscrm',
            name='estado',
            field=models.CharField(blank=True, help_text='Ex: Aberto, Fechado', max_length=50, null=True),
        ),
    ]
