# Generated by Django 5.2.1 on 2025-09-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_venda_data_pagamento_venda_valor_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': [('pode_reverter_status', 'Pode reverter o status de uma venda para etapas anteriores')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='venda',
            name='antecipou_instalacao',
            field=models.BooleanField(default=False, verbose_name='Houve antecipação de instalação?'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Instalação'),
        ),
        migrations.AddField(
            model_name='venda',
            name='motivo_pendencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_pendentes', to='crm_app.motivopendencia', verbose_name='Motivo da Pendência'),
        ),
    ]
