# Generated by Django 5.2.1 on 2025-09-16 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_alter_venda_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Venda Ativa'),
        ),
        migrations.AlterField(
            model_name='historicoalteracaovenda',
            name='alteracoes',
            field=models.JSONField(default=dict, help_text='Registra alterações ou a exclusão da venda'),
        ),
        migrations.AlterField(
            model_name='historicoalteracaovenda',
            name='venda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_alteracoes', to='crm_app.venda'),
        ),
    ]
