# Generated by Django 5.2.1 on 2025-11-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_venda_ativo_alter_historicoalteracaovenda_alteracoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nome_representante_legal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Representante'),
        ),
    ]
