# Generated by Django 5.2.1 on 2025-11-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0019_venda_nome_representante_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe'),
        ),
    ]
