# Generated by Django 5.2.1 on 2025-11-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_venda_data_nascimento_venda_nome_mae'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': [('pode_reverter_status', 'Pode reverter o status')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AddField(
            model_name='venda',
            name='data_pagamento_comissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data Pagamento Comissão'),
        ),
        migrations.AddField(
            model_name='venda',
            name='inclusao',
            field=models.BooleanField(default=False, verbose_name='Inclusão/Viabilidade'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='aplica_desconto',
            field=models.BooleanField(default=False, help_text='Aplica desconto de boleto?'),
        ),
        migrations.AlterField(
            model_name='motivopendencia',
            name='tipo_pendencia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='statuscrm',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='antecipou_instalacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_instalacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_pedido',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='motivo_pendencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_pendentes', to='crm_app.motivopendencia'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='nome_representante_legal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ordem_servico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='periodo_agendamento',
            field=models.CharField(blank=True, choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ponto_referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PagamentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_ano', models.IntegerField()),
                ('referencia_mes', models.IntegerField()),
                ('data_fechamento', models.DateTimeField(auto_now_add=True)),
                ('total_pago_consultores', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_recebido_ciclo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crm_pagamento_comissao',
                'ordering': ['-referencia_ano', '-referencia_mes'],
                'unique_together': {('referencia_ano', 'referencia_mes')},
            },
        ),
    ]
