# Generated by Django 5.2.1 on 2025-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0021_alter_venda_options_venda_data_pagamento_comissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
            },
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': [('pode_reverter_status', 'Pode reverter o status'), ('can_view_auditoria', 'Pode visualizar auditoria'), ('can_view_esteira', 'Pode visualizar esteira'), ('can_view_comissao_dashboard', 'Pode visualizar card de comissão')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
