# Generated by Django 5.2.1 on 2025-11-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_campanha_alter_venda_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoosab',
            name='campanha',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='cd_rede',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='celula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='classificacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='desc_motivo_ordem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='desc_sub_motivo_ordem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='fg_venda_valida',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='flg_mei',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='gerencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='gp_canal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='nm_diretoria',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importacaoosab',
            name='nm_regional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importacaoosab',
            name='numero_ba',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
