# Generated by Django 5.2.1 on 2025-11-28 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0023_importacaoosab_campanha_importacaoosab_cd_rede_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='auditor_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_em_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Em Auditoria Por'),
        ),
    ]
