# Generated by Django 5.2.1 on 2025-11-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0024_venda_auditor_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComissaoOperadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Base')),
                ('bonus_transicao', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bônus Transição')),
                ('data_inicio_bonus', models.DateField(blank=True, null=True, verbose_name='Início Bônus')),
                ('data_fim_bonus', models.DateField(blank=True, null=True, verbose_name='Fim Bônus')),
                ('plano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comissao_operadora', to='crm_app.plano', verbose_name='Plano')),
            ],
        ),
    ]
