# Generated by Django 5.2.1 on 2025-12-08 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_comissaooperadora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título Interno')),
                ('mensagem', models.TextField(verbose_name='Mensagem WhatsApp')),
                ('data_programada', models.DateField()),
                ('hora_programada', models.TimeField()),
                ('perfil_destino', models.CharField(choices=[('TODOS', 'Todos'), ('VENDEDOR', 'Vendedores'), ('SUPERVISOR', 'Supervisores'), ('BACKOFFICE', 'Backoffice'), ('DIRETORIA', 'Diretoria')], default='TODOS', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado (Record Informa)',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-data_programada', '-hora_programada'],
            },
        ),
    ]
