# Generated by Django 5.2.1 on 2025-12-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0027_alter_venda_forma_pagamento_alter_venda_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_kml', models.CharField(help_text='Nome que estava no Placemark', max_length=255)),
                ('celula', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('prioridade', models.IntegerField(blank=True, default=0, null=True)),
                ('estacao', models.CharField(blank=True, max_length=50, null=True)),
                ('aging', models.IntegerField(blank=True, default=0, null=True)),
                ('cluster', models.CharField(blank=True, max_length=50, null=True)),
                ('status_venda', models.CharField(blank=True, max_length=100, null=True)),
                ('hc', models.IntegerField(default=0, verbose_name='HC')),
                ('hp', models.IntegerField(default=0, verbose_name='HP')),
                ('hp_viavel', models.IntegerField(default=0, verbose_name='HP Viável')),
                ('hp_viavel_total', models.IntegerField(default=0, verbose_name='HP Viável Total')),
                ('ocupacao', models.CharField(blank=True, help_text='Percentual texto', max_length=20, null=True)),
                ('hc_esperado', models.FloatField(default=0.0)),
                ('atingimento_meta', models.CharField(blank=True, max_length=20, null=True)),
                ('coordenadas', models.TextField(blank=True, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Área de Venda (KML)',
                'verbose_name_plural': 'Áreas de Venda (KML)',
            },
        ),
    ]
