# Generated by Django 5.2.1 on 2025-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0028_areavenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('etapa', models.CharField(max_length=50)),
                ('dados_temp', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
