# Generated by Django 5.2.1 on 2025-12-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0029_sessaowhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('num_fachada', models.CharField(blank=True, help_text='Número da fachada', max_length=50, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_viabilidade', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_rede', models.CharField(blank=True, max_length=50, null=True)),
                ('celula', models.CharField(blank=True, max_length=50, null=True)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Base DFV',
                'verbose_name_plural': 'Base DFV',
                'indexes': [models.Index(fields=['cep'], name='crm_app_dfv_cep_bb7a7b_idx'), models.Index(fields=['cep', 'num_fachada'], name='crm_app_dfv_cep_0d2288_idx')],
            },
        ),
    ]
