# Generated by Django 5.2.1 on 2025-12-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0030_dfv'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDisparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Grupo Gestão Comercial', max_length=100)),
                ('chat_id', models.CharField(help_text='ID do grupo (Ex: 12036304...g.us)', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
