# Generated by Django 5.2.1 on 2025-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0031_grupodisparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='canal_alvo',
            field=models.CharField(choices=[('TODOS', 'Todos os Canais'), ('PAP', 'PAP'), ('DIGITAL', 'Digital'), ('RECEPTIVO', 'Receptivo'), ('PARCEIRO', 'Parceiro')], default='TODOS', max_length=20, verbose_name='Canal Alvo'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='descricao_premio',
            field=models.TextField(blank=True, help_text='Descrição da premiação', null=True, verbose_name='Prêmio'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='meta_vendas',
            field=models.IntegerField(default=0, help_text='Quantidade alvo de vendas'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='regras',
            field=models.TextField(blank=True, null=True, verbose_name='Regras'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='tipo_meta',
            field=models.CharField(choices=[('BRUTA', 'Vendas Brutas (OS Aberta)'), ('LIQUIDA', 'Vendas Líquidas (Instaladas)')], default='LIQUIDA', max_length=20, verbose_name='Tipo de Meta'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
