# Generated by Django 5.2.1 on 2025-12-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0032_campanha_canal_alvo_campanha_data_fim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanha',
            name='descricao_premio',
        ),
        migrations.AddField(
            model_name='campanha',
            name='formas_pagamento_elegiveis',
            field=models.ManyToManyField(blank=True, help_text='Se deixar vazio, vale para todas.', to='crm_app.formapagamento', verbose_name='Pagamentos Válidos'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='planos_elegiveis',
            field=models.ManyToManyField(blank=True, help_text='Se deixar vazio, vale para todos.', to='crm_app.plano', verbose_name='Planos Válidos'),
        ),
        migrations.AddField(
            model_name='campanha',
            name='valor_premio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor a ser pago se atingir a meta', max_digits=10, verbose_name='Prêmio em Dinheiro (R$)'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='regras',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Gerais'),
        ),
    ]
