# Generated by Django 5.2.1 on 2025-12-14 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0033_remove_campanha_descricao_premio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='descricao_premio',
            field=models.TextField(blank=True, help_text='Descrição da premiação', null=True, verbose_name='Prêmio'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='regras',
            field=models.TextField(blank=True, null=True, verbose_name='Regras'),
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADIANTAMENTO_CNPJ', 'Adiantamento CNPJ'), ('ADIANTAMENTO_COMISSAO', 'Adiantamento de Comissão'), ('DESCONTO', 'Desconto Avulso')], max_length=30)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_vendas', models.IntegerField(blank=True, default=0, help_text='Qtd de vendas (para Adiantamento CNPJ)', null=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição / Observação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_financeiros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lançamento Financeiro',
                'verbose_name_plural': 'Lançamentos Financeiros',
                'ordering': ['-data'],
            },
        ),
    ]
