# Generated by Django 5.2.1 on 2025-12-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0034_campanha_descricao_premio_alter_campanha_regras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='flag_adiant_cnpj',
            field=models.BooleanField(default=False, verbose_name='Adiant. CNPJ Processado'),
        ),
        migrations.AddField(
            model_name='venda',
            name='flag_desc_antecipacao',
            field=models.BooleanField(default=False, verbose_name='Desc. Antecip. Processado'),
        ),
        migrations.AddField(
            model_name='venda',
            name='flag_desc_boleto',
            field=models.BooleanField(default=False, verbose_name='Desc. Boleto Processado'),
        ),
        migrations.AddField(
            model_name='venda',
            name='flag_desc_viabilidade',
            field=models.BooleanField(default=False, verbose_name='Desc. Viab. Processado'),
        ),
    ]
