# Generated by Django 5.2.1 on 2025-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0035_venda_flag_adiant_cnpj_venda_flag_desc_antecipacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='metadados',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dados de Controle'),
        ),
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='quantidade_vendas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
