# Generated by Django 5.2.1 on 2025-12-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0036_lancamentofinanceiro_metadados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaowhatsapp',
            name='telefone',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
