# Generated by Django 5.2.1 on 2025-12-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0037_alter_sessaowhatsapp_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.IntegerField(verbose_name='Meta (Qtd Vendas)')),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prêmio (R$)')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_meta', to='crm_app.campanha')),
            ],
            options={
                'verbose_name': 'Faixa de Premiação',
                'verbose_name_plural': 'Faixas de Premiação',
                'ordering': ['-meta'],
            },
        ),
    ]
