# Generated by Django 5.2.1 on 2025-12-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0038_regracampanha'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Abertura da O.S'),
        ),
    ]
