# Generated by Django 5.2.1 on 2025-12-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0039_venda_data_abertura'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoDisparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HORARIO', 'Diário (Hora em Hora 9h-19h)'), ('SEMANAL', 'Semanal (Ter/Qui/Sáb 17h)')], max_length=20)),
                ('canal_alvo', models.CharField(choices=[('TODOS', 'Todos'), ('PAP', 'PAP'), ('DIGITAL', 'Digital'), ('RECEPTIVO', 'Receptivo'), ('PARCEIRO', 'Parceiro')], default='TODOS', max_length=20)),
                ('destinatarios', models.TextField(help_text='IDs de grupos ou números separados por vírgula')),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_disparo', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
