# Generated by Django 5.2.1 on 2025-12-27 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0040_agendamentodisparo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_ultima_alteracao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data da Última Alteração'),
        ),
        migrations.AddField(
            model_name='venda',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_editadas', to=settings.AUTH_USER_MODEL, verbose_name='Última alteração por'),
        ),
    ]
