# Generated by Django 5.2.1 on 2025-12-28 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0041_venda_data_ultima_alteracao_venda_editado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CdoiSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_condominio', models.CharField(max_length=255)),
                ('nome_sindico', models.CharField(max_length=255)),
                ('contato_sindico', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_sap', models.CharField(default='1068561', max_length=50)),
                ('infraestrutura_tipo', models.CharField(choices=[('INTERNA', 'Interna'), ('FACHADA', 'Fachada')], max_length=50)),
                ('possui_shaft_dg', models.BooleanField(default=False, verbose_name='Possui Shaft/DG?')),
                ('total_blocos', models.IntegerField(default=0)),
                ('total_hps', models.IntegerField(default=0)),
                ('pre_venda_minima', models.IntegerField(default=0, help_text='10% do Total de HPs')),
                ('link_carta_sindico', models.URLField(blank=True, max_length=500, null=True)),
                ('link_fotos_fachada', models.URLField(blank=True, max_length=500, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='EM ANÁLISE', max_length=50)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CdoiBloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bloco', models.CharField(max_length=100)),
                ('andares', models.IntegerField()),
                ('unidades_por_andar', models.IntegerField()),
                ('total_hps_bloco', models.IntegerField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='crm_app.cdoisolicitacao')),
            ],
        ),
    ]
