# Generated by Django 5.2.1 on 2025-12-28 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0042_cdoisolicitacao_cdoibloco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdoisolicitacao',
            name='codigo_sap',
        ),
        migrations.RemoveField(
            model_name='cdoisolicitacao',
            name='total_blocos',
        ),
        migrations.AddField(
            model_name='cdoisolicitacao',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Backoffice'),
        ),
        migrations.AlterField(
            model_name='cdoisolicitacao',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='cdoisolicitacao',
            name='contato_sindico',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cdoisolicitacao',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdoisolicitacao',
            name='infraestrutura_tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cdoisolicitacao',
            name='numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cdoisolicitacao',
            name='possui_shaft_dg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cdoisolicitacao',
            name='pre_venda_minima',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cdoisolicitacao',
            name='status',
            field=models.CharField(choices=[('SEM_TRATAMENTO', 'Sem tratamento'), ('EM_CADASTRO', 'Em cadastro'), ('EM_PROJETO', 'Em Projeto'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDA', 'Concluída')], default='SEM_TRATAMENTO', max_length=50),
        ),
    ]
