# Generated by Django 5.2.1 on 2025-12-31 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0043_remove_cdoisolicitacao_codigo_sap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafraM10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Mês/Ano da safra (ex: 2025-07-01)')),
                ('total_instalados', models.IntegerField(default=0, help_text='Total de contratos instalados na safra')),
                ('total_ativos', models.IntegerField(default=0, help_text='Total ainda ativo')),
                ('total_elegivel_bonus', models.IntegerField(default=0, help_text='Elegíveis para bônus M-10')),
                ('valor_bonus_total', models.DecimalField(decimal_places=2, default=0, help_text='Total a pagar (elegíveis × R$ 150)', max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Safra M-10',
                'verbose_name_plural': 'Safras M-10',
                'ordering': ['-mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='ContratoM10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100, unique=True)),
                ('cliente_nome', models.CharField(max_length=255)),
                ('data_instalacao', models.DateField()),
                ('plano_original', models.CharField(max_length=100)),
                ('plano_atual', models.CharField(max_length=100)),
                ('valor_plano', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status_contrato', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado'), ('DOWNGRADE', 'Downgrade')], default='ATIVO', max_length=20)),
                ('teve_downgrade', models.BooleanField(default=False, help_text='Marca manual se houve downgrade')),
                ('data_cancelamento', models.DateField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=255, null=True)),
                ('elegivel_bonus', models.BooleanField(default=False, help_text='10 faturas pagas + sem downgrade + ativo')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_m10', to='crm_app.venda')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('safra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='crm_app.safram10')),
            ],
            options={
                'verbose_name': 'Contrato M-10',
                'verbose_name_plural': 'Contratos M-10',
                'ordering': ['-data_instalacao'],
            },
        ),
        migrations.CreateModel(
            name='FaturaM10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fatura', models.IntegerField(help_text='1 a 10')),
                ('numero_fatura_operadora', models.CharField(blank=True, help_text='NR_FATURA da planilha', max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('dias_atraso', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('NAO_PAGO', 'Não Pago'), ('AGUARDANDO', 'Aguardando Arrecadação'), ('ATRASADO', 'Atrasado'), ('OUTROS', 'Outros')], default='NAO_PAGO', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='crm_app.contratom10')),
            ],
            options={
                'verbose_name': 'Fatura M-10',
                'verbose_name_plural': 'Faturas M-10',
                'ordering': ['contrato', 'numero_fatura'],
                'unique_together': {('contrato', 'numero_fatura')},
            },
        ),
    ]
