# Generated by Django 5.2.1 on 2025-12-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0044_safram10_contratom10_faturam10'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratom10',
            name='cpf_cliente',
            field=models.CharField(blank=True, help_text='CPF do cliente', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='contratom10',
            name='ordem_servico',
            field=models.CharField(blank=True, help_text='O.S para crossover com FPD/Churn', max_length=100, null=True, unique=True),
        ),
    ]
