# Generated by Django 5.2.1 on 2025-12-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0045_add_ordem_servico_cpf_to_contratom10'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('nm_municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='MunicÃ\xadpio')),
                ('indicador', models.CharField(blank=True, max_length=255, null=True, verbose_name='Indicador')),
                ('cd_nrba', models.CharField(blank=True, max_length=255, null=True, verbose_name='CÃ³digo NRBA')),
                ('st_ba', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status BA')),
                ('cd_encerramento', models.CharField(blank=True, max_length=255, null=True, verbose_name='CÃ³digo Encerramento')),
                ('desc_observacao', models.TextField(blank=True, null=True, verbose_name='ObservaÃ§Ã£o')),
                ('desc_macro_atividade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Macro Atividade')),
                ('ds_atividade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Atividade')),
                ('dt_abertura_ba', models.DateField(blank=True, null=True, verbose_name='Data Abertura BA')),
                ('dt_inicio_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='InÃ\xadcio Agendamento')),
                ('dt_fim_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='Fim Agendamento')),
                ('dt_inicio_execucao_real', models.DateTimeField(blank=True, null=True, verbose_name='InÃ\xadcio ExecuÃ§Ã£o Real')),
                ('dt_fim_execucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Fim ExecuÃ§Ã£o Real')),
                ('nr_ordem', models.CharField(blank=True, max_length=255, null=True, verbose_name='NÃºmero Ordem')),
                ('nr_ordem_venda', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ordem Venda')),
                ('dt_execucao_particao', models.DateField(blank=True, null=True, verbose_name='Data ExecuÃ§Ã£o PartiÃ§Ã£o')),
                ('anomes', models.CharField(blank=True, max_length=6, null=True, verbose_name='Ano/MÃªs')),
                ('cd_sap_original', models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP Original')),
                ('cd_rede', models.CharField(blank=True, max_length=255, null=True, verbose_name='CÃ³digo Rede')),
                ('nm_pdv_rel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome PDV')),
                ('rede', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rede')),
                ('gp_canal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Canal')),
                ('sg_gerencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sigla GerÃªncia')),
                ('nm_gc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome GC')),
                ('dt_agendamento', models.DateField(blank=True, null=True, verbose_name='Data Agendamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'ImportaÃ§Ã£o Agendamento',
                'verbose_name_plural': 'ImportaÃ§Ãµes Agendamentos',
                'ordering': ['-dt_agendamento', '-criado_em'],
                'indexes': [models.Index(fields=['cd_nrba'], name='crm_app_imp_cd_nrba_6af682_idx'), models.Index(fields=['nr_ordem'], name='crm_app_imp_nr_orde_deca4f_idx'), models.Index(fields=['dt_agendamento'], name='crm_app_imp_dt_agen_9fed94_idx'), models.Index(fields=['anomes'], name='crm_app_imp_anomes_8edddb_idx')],
            },
        ),
    ]
