# Generated by Django 5.2.1 on 2025-12-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0046_importacaoagendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoRecompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_anomes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ano/Mês')),
                ('nr_ordem', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Número Ordem')),
                ('dt_venda_particao', models.DateField(blank=True, null=True, verbose_name='Data Venda Partição')),
                ('dt_encerramento', models.DateField(blank=True, null=True, verbose_name='Data Encerramento')),
                ('dt_inicio_ativo', models.DateField(blank=True, null=True, verbose_name='Data Início Ativo')),
                ('st_ordem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status Ordem')),
                ('nm_seg', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Segmento')),
                ('resultado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resultado')),
                ('sg_uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('nm_municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Município')),
                ('nm_bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('nr_cep', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP')),
                ('nr_cep_base', models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP Base')),
                ('nr_complemento1_base', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento 1')),
                ('nr_complemento2_base', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento 2')),
                ('nr_complemento3_base', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento 3')),
                ('cd_sap_pdv', models.CharField(blank=True, max_length=255, null=True, verbose_name='SAP PDV')),
                ('cd_tr_vdd', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transação Vendedor')),
                ('nm_diretoria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Diretoria')),
                ('nm_regional', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regional')),
                ('cd_rede', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código Rede')),
                ('gp_canal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo Canal')),
                ('nm_pdv_rel', models.CharField(blank=True, max_length=255, null=True, verbose_name='PDV Relacionado')),
                ('nm_gc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gerente de Conta')),
                ('GERENCIA', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gerência')),
                ('REDE', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rede')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Importação Recompra',
                'verbose_name_plural': 'Importações Recompra',
                'ordering': ['-dt_venda_particao', '-created_at'],
                'indexes': [models.Index(fields=['nr_ordem'], name='crm_app_imp_nr_orde_0dc32c_idx'), models.Index(fields=['ds_anomes'], name='crm_app_imp_ds_anom_6275f6_idx'), models.Index(fields=['dt_venda_particao'], name='crm_app_imp_dt_vend_1a43cc_idx'), models.Index(fields=['sg_uf'], name='crm_app_imp_sg_uf_f43317_idx')],
            },
        ),
    ]
