# Generated by Django 5.2.1 on 2025-12-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0047_importacaorecompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturam10',
            name='arquivo_pdf',
            field=models.FileField(blank=True, help_text='PDF da fatura', null=True, upload_to='faturas_m10/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras da fatura', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='codigo_pix',
            field=models.TextField(blank=True, help_text='Código PIX Copia e Cola', null=True),
        ),
    ]
