# Generated by Django 5.2.1 on 2025-12-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0048_faturam10_arquivo_pdf_faturam10_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratom10',
            name='numero_contrato_definitivo',
            field=models.CharField(blank=True, help_text='Número do contrato definitivo (vem do FPD)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratom10',
            name='numero_contrato',
            field=models.CharField(help_text='Número da O.S/PEDIDO', max_length=100, unique=True),
        ),
    ]
