# Generated by Django 5.2.1 on 2025-12-31 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0049_contratom10_numero_contrato_definitivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturam10',
            name='data_importacao_fpd',
            field=models.DateTimeField(blank=True, help_text='Data da última importação FPD', null=True),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='ds_status_fatura_fpd',
            field=models.CharField(blank=True, help_text='DS_STATUS_FATURA do arquivo FPD', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='dt_pagamento_fpd',
            field=models.DateField(blank=True, help_text='DT_PAGAMENTO do arquivo FPD', null=True),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='id_contrato_fpd',
            field=models.CharField(blank=True, help_text='ID_CONTRATO do arquivo FPD', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ImportacaoFPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_ordem', models.CharField(db_index=True, help_text='Número de Ordem (O.S)', max_length=100)),
                ('id_contrato', models.CharField(help_text='ID_CONTRATO do arquivo FPD', max_length=100)),
                ('nr_fatura', models.CharField(help_text='NR_FATURA do arquivo FPD', max_length=100)),
                ('dt_venc_orig', models.DateField(help_text='Data de vencimento original')),
                ('dt_pagamento', models.DateField(blank=True, help_text='Data de pagamento', null=True)),
                ('nr_dias_atraso', models.IntegerField(default=0, help_text='Número de dias em atraso')),
                ('ds_status_fatura', models.CharField(help_text='Status da fatura (PAGO, ABERTO, VENCIDO, etc)', max_length=50)),
                ('vl_fatura', models.DecimalField(decimal_places=2, default=0, help_text='Valor da fatura', max_digits=10)),
                ('importada_em', models.DateTimeField(auto_now_add=True, help_text='Data da importação')),
                ('atualizada_em', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('contrato_m10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importacoes_fpd', to='crm_app.contratom10')),
            ],
            options={
                'verbose_name': 'Importação FPD',
                'verbose_name_plural': 'Importações FPD',
                'ordering': ['-importada_em', 'nr_ordem'],
                'indexes': [models.Index(fields=['nr_ordem'], name='crm_app_imp_nr_orde_d7ad9f_idx'), models.Index(fields=['id_contrato'], name='crm_app_imp_id_cont_c15efa_idx'), models.Index(fields=['ds_status_fatura'], name='crm_app_imp_ds_stat_524bf1_idx'), models.Index(fields=['dt_venc_orig'], name='crm_app_imp_dt_venc_3a2a8d_idx')],
                'unique_together': {('nr_ordem', 'nr_fatura')},
            },
        ),
    ]
