# Generated by Django 5.2.1 on 2025-12-31 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0050_add_fpd_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogImportacaoFPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(help_text='Nome do arquivo importado', max_length=255)),
                ('tamanho_arquivo', models.IntegerField(help_text='Tamanho do arquivo em bytes')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Sucesso Parcial')], default='PROCESSANDO', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.IntegerField(blank=True, help_text='Duração em segundos', null=True)),
                ('total_linhas', models.IntegerField(default=0, help_text='Total de linhas no arquivo')),
                ('total_processadas', models.IntegerField(default=0, help_text='Linhas processadas com sucesso')),
                ('total_erros', models.IntegerField(default=0, help_text='Linhas com erro')),
                ('total_contratos_nao_encontrados', models.IntegerField(default=0, help_text='Contratos M10 não encontrados')),
                ('total_valor_importado', models.DecimalField(decimal_places=2, default=0, help_text='Valor total importado', max_digits=15)),
                ('mensagem_erro', models.TextField(blank=True, help_text='Mensagem de erro se houver', null=True)),
                ('detalhes_json', models.JSONField(blank=True, default=dict, help_text='Detalhes adicionais em JSON')),
                ('exemplos_nao_encontrados', models.TextField(blank=True, help_text='Primeiras 10 O.S não encontradas', null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_importacao_fpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Importação FPD',
                'verbose_name_plural': 'Logs Importações FPD',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['status'], name='crm_app_log_status_94b9e5_idx'), models.Index(fields=['iniciado_em'], name='crm_app_log_iniciad_22bd2c_idx'), models.Index(fields=['usuario'], name='crm_app_log_usuario_6d8367_idx')],
            },
        ),
    ]
