# Generated by Django 5.2.1 on 2026-01-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0051_add_log_importacao_fpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaochurn',
            name='nr_ordem',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Número da Ordem (O.S)'),
        ),
    ]
