# Generated by Django 5.2.1 on 2026-01-01 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0053_logimportacaochurn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importacaofpd',
            options={'ordering': ['-importada_em'], 'verbose_name': 'Importação FPD', 'verbose_name_plural': 'Importações FPD'},
        ),
        migrations.AlterModelOptions(
            name='logimportacaofpd',
            options={'ordering': ['-data_importacao'], 'verbose_name': 'Log Importação FPD', 'verbose_name_plural': 'Logs Importação FPD'},
        ),
        migrations.RemoveIndex(
            model_name='importacaofpd',
            name='crm_app_imp_dt_venc_3a2a8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='logimportacaofpd',
            name='crm_app_log_status_94b9e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='logimportacaofpd',
            name='crm_app_log_iniciad_22bd2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='logimportacaofpd',
            name='crm_app_log_usuario_6d8367_idx',
        ),
        migrations.RenameField(
            model_name='logimportacaofpd',
            old_name='iniciado_em',
            new_name='data_importacao',
        ),
        migrations.AlterUniqueTogether(
            name='importacaofpd',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='faturam10',
            name='arquivo_pdf',
        ),
        migrations.RemoveField(
            model_name='faturam10',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='faturam10',
            name='codigo_pix',
        ),
        migrations.RemoveField(
            model_name='faturam10',
            name='data_importacao_fpd',
        ),
        migrations.RemoveField(
            model_name='faturam10',
            name='ds_status_fatura_fpd',
        ),
        migrations.RemoveField(
            model_name='faturam10',
            name='dt_pagamento_fpd',
        ),
        migrations.RemoveField(
            model_name='faturam10',
            name='id_contrato_fpd',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='detalhes_json',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='duracao_segundos',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='exemplos_nao_encontrados',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='finalizado_em',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='mensagem_erro',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='tamanho_arquivo',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='total_contratos_nao_encontrados',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='total_erros',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='total_processadas',
        ),
        migrations.RemoveField(
            model_name='logimportacaofpd',
            name='total_valor_importado',
        ),
        migrations.AddField(
            model_name='contratom10',
            name='data_ultima_sincronizacao_fpd',
            field=models.DateTimeField(blank=True, help_text='Última sincronização com FPD', null=True),
        ),
        migrations.AddField(
            model_name='importacaofpd',
            name='numero_os',
            field=models.CharField(blank=True, db_index=True, help_text='Alternativa NR_OS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logimportacaofpd',
            name='erros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logimportacaofpd',
            name='mensagem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logimportacaofpd',
            name='sucesso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contratom10',
            name='numero_contrato',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contratom10',
            name='numero_contrato_definitivo',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente do FPD', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='importacaochurn',
            name='nr_ordem',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Número de Ordem'),
        ),
        migrations.AlterField(
            model_name='logimportacaofpd',
            name='nome_arquivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logimportacaofpd',
            name='status',
            field=models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Parcial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logimportacaofpd',
            name='total_linhas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logimportacaofpd',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
