# Generated by Django 5.2.1 on 2026-01-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0054_add_fpd_fields_contrato_m10'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratom10',
            name='data_pagamento_fpd',
            field=models.DateField(blank=True, help_text='Data de pagamento da última fatura FPD', null=True),
        ),
        migrations.AddField(
            model_name='contratom10',
            name='data_vencimento_fpd',
            field=models.DateField(blank=True, help_text='Data de vencimento da última fatura FPD', null=True),
        ),
        migrations.AddField(
            model_name='contratom10',
            name='nr_dias_atraso_fpd',
            field=models.IntegerField(blank=True, help_text='Dias em atraso da última fatura FPD', null=True),
        ),
        migrations.AddField(
            model_name='contratom10',
            name='status_fatura_fpd',
            field=models.CharField(blank=True, help_text='Status da última fatura FPD (PAGO, ABERTO, etc)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contratom10',
            name='valor_fatura_fpd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da última fatura FPD', max_digits=10, null=True),
        ),
    ]
