# Generated by Django 5.2.1 on 2026-01-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0057_faturam10_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturam10',
            name='data_disponibilidade',
            field=models.DateField(blank=True, help_text='Data em que a fatura estará disponível no Nio', null=True),
        ),
        migrations.AlterField(
            model_name='contratom10',
            name='safra',
            field=models.CharField(blank=True, help_text='Mês/Ano da instalação (YYYY-MM)', max_length=7, null=True),
        ),
    ]
