# Generated by Django 5.2.1 on 2026-01-02 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0058_adicionar_safra_e_disponibilidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faturam10',
            name='erro_busca',
            field=models.TextField(blank=True, help_text='Mensagem de erro da última busca', null=True),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='origem_busca',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Busca Manual'), ('AUTOMATICA', 'Busca Automática (Agendada)'), ('SAFRA', 'Busca por Safra'), ('INDIVIDUAL', 'Busca Individual')], help_text='Origem da última busca', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='status_busca',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Parcial')], default='PENDENTE', help_text='Status da última busca', max_length=20),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='tempo_busca_segundos',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Tempo de execução da busca em segundos', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='tentativas_busca',
            field=models.IntegerField(default=0, help_text='Número de tentativas de busca'),
        ),
        migrations.AddField(
            model_name='faturam10',
            name='ultima_busca_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora da última tentativa de busca', null=True),
        ),
        migrations.CreateModel(
            name='HistoricoBuscaFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_busca', models.CharField(choices=[('AUTOMATICA', 'Busca Automática (Agendada)'), ('SAFRA', 'Busca por Safra'), ('INDIVIDUAL', 'Busca Individual'), ('RETRY', 'Retry de Erro')], help_text='Tipo de execução', max_length=20)),
                ('safra', models.CharField(blank=True, help_text='Safra processada (formato YYYY-MM)', max_length=7, null=True)),
                ('inicio_em', models.DateTimeField(auto_now_add=True)),
                ('termino_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_contratos', models.IntegerField(default=0)),
                ('total_faturas', models.IntegerField(default=0)),
                ('faturas_sucesso', models.IntegerField(default=0)),
                ('faturas_erro', models.IntegerField(default=0)),
                ('faturas_nao_disponiveis', models.IntegerField(default=0)),
                ('faturas_retry', models.IntegerField(default=0)),
                ('tempo_medio_fatura', models.DecimalField(blank=True, decimal_places=3, help_text='Tempo médio por fatura (segundos)', max_digits=8, null=True)),
                ('tempo_min_fatura', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('tempo_max_fatura', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20)),
                ('mensagem', models.TextField(blank=True, help_text='Mensagem final ou erro', null=True)),
                ('logs', models.JSONField(blank=True, help_text='Logs detalhados da execução', null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que iniciou', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Busca de Fatura',
                'verbose_name_plural': 'Histórico de Buscas de Faturas',
                'ordering': ['-inicio_em'],
            },
        ),
    ]
