# Generated by Django 5.2.1 on 2026-01-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0060_restore_fpd_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logimportacaofpd',
            name='iniciado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
