# Generated by Django 5.2.1 on 2026-01-03 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0062_logimportacaoosab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogImportacaoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Parcial')], max_length=20)),
                ('tamanho_arquivo', models.IntegerField(blank=True, default=0, null=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.IntegerField(blank=True, null=True)),
                ('total_linhas', models.IntegerField(default=0)),
                ('total_processadas', models.IntegerField(default=0)),
                ('agendamentos_criados', models.IntegerField(default=0)),
                ('agendamentos_atualizados', models.IntegerField(default=0)),
                ('nao_encontrados', models.IntegerField(default=0)),
                ('erros_count', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('detalhes_json', models.JSONField(blank=True, default=dict, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Importação Agendamento',
                'verbose_name_plural': 'Logs Importação Agendamento',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogImportacaoLegado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Parcial')], max_length=20)),
                ('tamanho_arquivo', models.IntegerField(blank=True, default=0, null=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.IntegerField(blank=True, null=True)),
                ('total_linhas', models.IntegerField(default=0)),
                ('total_processadas', models.IntegerField(default=0)),
                ('vendas_criadas', models.IntegerField(default=0)),
                ('vendas_atualizadas', models.IntegerField(default=0)),
                ('clientes_criados', models.IntegerField(default=0)),
                ('erros_count', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('detalhes_json', models.JSONField(blank=True, default=dict, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Importação Legado',
                'verbose_name_plural': 'Logs Importação Legado',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
