# Generated by Django 5.2.1 on 2026-01-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0064_logimportacaodfv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaoosab',
            name='documento',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_instalacao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ordem_servico',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
