# Generated by ChatGPT on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0066_create_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdoisolicitacao',
            name='destinatarios_resumo',
            field=models.TextField(blank=True, help_text='Telefones extras para resumo', null=True),
        ),
    ]
