# Generated by Django 5.2.1 on 2026-01-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_dfv_nome_cdo'),
        ('crm_app', '0067_cdoi_destinatarios_resumo'),
    ]

    operations = [
    ]
