# Generated by Django 5.2.1 on 2026-01-17 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0068_merge_20260115_1201'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticaBotWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, help_text='Telefone do usuário que recebeu a mensagem', max_length=100)),
                ('comando', models.CharField(choices=[('FACHADA', 'Fachada'), ('VIABILIDADE', 'Viabilidade'), ('FATURA', 'Fatura'), ('STATUS', 'Status')], db_index=True, max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estatisticas_bot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estatística Bot WhatsApp',
                'verbose_name_plural': 'Estatísticas Bot WhatsApp',
                'indexes': [models.Index(fields=['comando', 'data_envio'], name='crm_app_est_comando_3b4832_idx'), models.Index(fields=['vendedor', 'data_envio'], name='crm_app_est_vendedo_80a366_idx'), models.Index(fields=['data_envio'], name='crm_app_est_data_en_3aa173_idx')],
            },
        ),
    ]
