# Generated by Django 5.2.1 on 2026-01-18 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0070_logimportacaorecompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordApoia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Arquivo a ser armazenado', upload_to='record_apoia/%Y/%m/%d/')),
                ('nome_original', models.CharField(help_text='Nome original do arquivo no upload', max_length=255)),
                ('tipo_arquivo', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word (DOC/DOCX)'), ('EXCEL', 'Excel (XLS/XLSX)'), ('IMAGEM', 'Imagem (JPG/PNG/GIF)'), ('VIDEO', 'Vídeo (MP4/AVI/MOV)'), ('OUTRO', 'Outro')], help_text='Tipo/categoria do arquivo', max_length=20)),
                ('tamanho_bytes', models.BigIntegerField(default=0, help_text='Tamanho do arquivo em bytes')),
                ('titulo', models.CharField(help_text='Título/descrição do arquivo', max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada (opcional)', null=True)),
                ('categoria', models.CharField(blank=True, help_text='Categoria/tag para organização (ex: Manual, Treinamento, Documentação)', max_length=100, null=True)),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula (ex: urgente, importante, tutorial)', max_length=500, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True, help_text='Data e hora do upload')),
                ('downloads_count', models.IntegerField(default=0, help_text='Contador de downloads')),
                ('ativo', models.BooleanField(default=True, help_text='Se False, arquivo está oculto (soft delete)')),
                ('usuario_upload', models.ForeignKey(blank=True, help_text='Usuário que fez o upload', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_uploadados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arquivo Record Apoia',
                'verbose_name_plural': 'Arquivos Record Apoia',
                'ordering': ['-data_upload'],
                'indexes': [models.Index(fields=['tipo_arquivo'], name='crm_app_rec_tipo_ar_9d7431_idx'), models.Index(fields=['categoria'], name='crm_app_rec_categor_871e3d_idx'), models.Index(fields=['data_upload'], name='crm_app_rec_data_up_1b817a_idx'), models.Index(fields=['ativo'], name='crm_app_rec_ativo_b7cb1b_idx')],
            },
        ),
    ]
