# Generated by Django 5.2.1 on 2026-01-21 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0071_recordapoia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motivopendencia',
            options={'ordering': ['nome'], 'verbose_name': 'Motivo de Pendência', 'verbose_name_plural': 'Motivos de Pendência'},
        ),
        migrations.CreateModel(
            name='PreVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('telefone_whatsapp', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('anexo', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Anexo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Pré-venda',
                'verbose_name_plural': 'Pré-vendas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
