# Generated by Django 5.2.1 on 2026-01-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def limpar_prevendas_antigas(apps, schema_editor):
    """Remove registros antigos de PreVenda que não são compatíveis com a nova estrutura"""
    PreVenda = apps.get_model('crm_app', 'PreVenda')
    # Deleta todos os registros antigos (estrutura antiga não é compatível)
    PreVenda.objects.all().delete()


def reverter_limpeza(apps, schema_editor):
    """Função reversa (não faz nada, pois não podemos restaurar dados deletados)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0072_alter_motivopendencia_options_prevenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Primeiro, limpa os dados antigos
        migrations.RunPython(limpar_prevendas_antigas, reverter_limpeza),
        
        # Cria o modelo LinkPublicoPreVenda
        migrations.CreateModel(
            name='LinkPublicoPreVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Código Único')),
                ('imagem_banner', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem/Banner')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Link Ativo')),
                ('acionamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_prevenda', to='crm_app.cdoisolicitacao', verbose_name='Acionamento CDOI')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Link Público Pré-venda',
                'verbose_name_plural': 'Links Públicos Pré-vendas',
                'ordering': ['-data_criacao'],
            },
        ),
        
        # Altera opções do modelo PreVenda
        migrations.AlterModelOptions(
            name='prevenda',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Pré-venda', 'verbose_name_plural': 'Pré-vendas'},
        ),
        
        # Remove campos antigos
        migrations.RemoveField(
            model_name='prevenda',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='prevenda',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='prevenda',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='prevenda',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='prevenda',
            name='observacoes',
        ),
        
        # Adiciona novos campos
        migrations.AddField(
            model_name='prevenda',
            name='apartamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apartamento'),
        ),
        migrations.AddField(
            model_name='prevenda',
            name='bloco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bloco'),
        ),
        migrations.AddField(
            model_name='prevenda',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prevenda',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='prevenda',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem'),
        ),
        
        # Adiciona o campo link_publico (FK obrigatório) - Como já limpamos os dados, não precisa de default
        migrations.AddField(
            model_name='prevenda',
            name='link_publico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prevendas', to='crm_app.linkpublicoprevenda', verbose_name='Link Público'),
        ),
    ]
