# Generated by Django 5.2.1 on 2026-01-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0073_alter_prevenda_options_remove_prevenda_anexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpublicoprevenda',
            name='imagem_banner',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL da Imagem/Banner'),
        ),
    ]
