# Generated by Django 5.2.1 on 2026-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0074_alter_linkpublicoprevenda_imagem_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='tem_fixo',
            field=models.BooleanField(default=False, verbose_name='Tem Fixo'),
        ),
    ]
