# Generated by Django 5.2.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0075_add_tem_fixo_to_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PapBoEmUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_telefone', models.CharField(db_index=True, max_length=100)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('sessao_whatsapp_id', models.IntegerField(blank=True, null=True)),
                ('bo_usuario', models.ForeignKey(help_text='Usuário BackOffice cujo login está em uso', on_delete=django.db.models.deletion.CASCADE, related_name='pap_sessoes_em_uso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PAP BO em Uso',
                'verbose_name_plural': 'PAP BOs em Uso',
                'db_table': 'crm_pap_bo_em_uso',
            },
        ),
    ]
