# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0076_add_pap_bo_em_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='agencia_dacc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência DACC'),
        ),
        migrations.AddField(
            model_name='venda',
            name='banco_dacc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco DACC'),
        ),
        migrations.AddField(
            model_name='venda',
            name='conta_dacc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Conta DACC'),
        ),
        migrations.AddField(
            model_name='venda',
            name='digito_dacc',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Dígito DACC'),
        ),
    ]
