# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0077_add_dacc_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapConfirmacaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular_cliente', models.CharField(db_index=True, max_length=20)),
                ('confirmado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PAP Confirmação Cliente',
                'db_table': 'crm_pap_confirmacao_cliente',
                'ordering': ['-criado_em'],
            },
        ),
    ]
