# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0078_add_pap_confirmacao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='gerada_os_automatica',
            field=models.BooleanField(default=False, help_text='Se a venda foi gerada com O.S. automática (vendedor já abriu o pedido).', verbose_name='Gerada O.S. automática'),
        ),
    ]
