# Generated by Django 5.2.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0079_add_gerada_os_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='papconfirmacaocliente',
            name='sessao',
            field=models.ForeignKey(
                blank=True,
                db_column='sessao_id',
                db_index=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='pap_confirmacoes',
                to='crm_app.sessaowhatsapp',
            ),
        ),
    ]
