# Generated by Django 5.2.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm_app', '0080_pap_confirmacao_cliente_sessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseCreditoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_consultado', models.CharField(db_index=True, help_text='CPF consultado (apenas dígitos)', max_length=14)),
                ('aprovado', models.BooleanField(help_text='True se crédito aprovado, False se negado')),
                ('resultado_detalhe', models.CharField(blank=True, help_text='Ex: Elegível para todas as formas, Elegível apenas para Cartão', max_length=200, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(help_text='Usuário que fez a consulta', on_delete=django.db.models.deletion.CASCADE, related_name='analises_credito_historico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análise de Crédito (Histórico)',
                'verbose_name_plural': 'Análises de Crédito (Histórico)',
                'db_table': 'crm_analise_credito_historico',
                'ordering': ['-criado_em'],
                'indexes': [
                    models.Index(fields=['usuario', 'criado_em'], name='crm_analise_usuario_criado_idx'),
                ],
            },
        ),
    ]
