# Generated by Django 5.2.1 on 2026-02-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0081_add_analise_credito_historico'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analisecreditohistorico',
            new_name='crm_analise_usuario_08f1dc_idx',
            old_name='crm_analise_usuario_criado_idx',
        ),
        migrations.AlterField(
            model_name='estatisticabotwhatsapp',
            name='comando',
            field=models.CharField(choices=[('FACHADA', 'Fachada'), ('VIABILIDADE', 'Viabilidade'), ('FATURA', 'Fatura'), ('STATUS', 'Status'), ('CREDITO', 'Crédito')], db_index=True, max_length=20),
        ),
    ]
