# Generated by Django 5.2.1 on 2026-02-17 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0082_rename_crm_analise_usuario_criado_idx_crm_analise_usuario_08f1dc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnteciparInstalacaoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_gc', models.CharField(blank=True, default='21979630377', max_length=20, verbose_name='Telefone do GC')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm_app.grupodisparo', verbose_name='Grupo WhatsApp (ex: Record PAP)')),
            ],
            options={
                'verbose_name': 'Config. Antecipar Instalação',
                'verbose_name_plural': 'Config. Antecipar Instalação',
            },
        ),
        migrations.CreateModel(
            name='AnteciparInstalacaoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_servico', models.CharField(blank=True, max_length=50)),
                ('descricao_solicitacao', models.TextField()),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('enviado_gc', models.BooleanField(default=False)),
                ('enviado_grupo', models.BooleanField(default=False)),
                ('erros', models.JSONField(blank=True, default=list)),
                ('mensagem_enviada', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_antecipar', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_antecipar', to='crm_app.venda')),
            ],
            options={
                'verbose_name': 'Solicitação Antecipar Instalação',
                'verbose_name_plural': 'Solicitações Antecipar Instalação',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
