# Generated by Django 5.2.1 on 2026-02-17 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0083_antecipar_instalacao_config_historico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigComissaoVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_comissao', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Supervisor', 'Supervisor')], default='Vendedor', max_length=20)),
                ('usar_valor_manual', models.BooleanField(default=False, verbose_name='Usar valor manual?')),
                ('valor_500mb_pap_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_700mb_pap_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_1gb_pap_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_500mb_cnpj_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_700mb_cnpj_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_1gb_cnpj_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desconta_dacc_pap', models.BooleanField(default=False, verbose_name='Desconta DACC PAP?')),
                ('desconto_boleto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('desconto_inclusao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('desconto_instalacao', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('adiantar_cnpj', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('inss_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adiantamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premiação', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_cartao_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cartao_trafego', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gestor_trafego', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_comissao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config. Comissão Vendedor',
                'verbose_name_plural': 'Config. Comissão Vendedores',
                'db_table': 'crm_config_comissao_vendedor',
            },
        ),
        migrations.CreateModel(
            name='RegraComissaoFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(blank=True, choices=[('Vendedor', 'Vendedor'), ('Supervisor', 'Supervisor')], help_text='Vazio se for regra individual (vendedor preenchido)', max_length=50, null=True)),
                ('faixa_nome', models.CharField(max_length=100)),
                ('min_vendas', models.PositiveIntegerField(default=0)),
                ('max_vendas', models.PositiveIntegerField(default=99999, help_text='Use 99999 para sem teto')),
                ('valor_500mb_pap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_700mb_pap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_1gb_pap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_500mb_cnpj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_700mb_cnpj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_1gb_cnpj', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendedor', models.ForeignKey(blank=True, help_text='Preenchido quando a regra é só para este vendedor (ex.: ALEX)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao_faixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Regra de Comissão por Faixa',
                'verbose_name_plural': 'Regras de Comissão por Faixa',
                'db_table': 'crm_regra_comissao_faixa',
                'ordering': ['perfil', 'vendedor', 'min_vendas'],
            },
        ),
    ]
