# Generated by Django 5.2.1 on 2026-02-17 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0084_regras_comissao_faixa_config_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configcomissaovendedor',
            name='ano',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ano de referência (nulo = modelo padrão)', null=True),
        ),
        migrations.AddField(
            model_name='configcomissaovendedor',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Mês de referência (1-12, nulo = modelo padrão)', null=True),
        ),
        migrations.AlterField(
            model_name='configcomissaovendedor',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs_comissao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='configcomissaovendedor',
            constraint=models.UniqueConstraint(condition=models.Q(('ano__isnull', False), ('mes__isnull', False)), fields=('usuario', 'ano', 'mes'), name='crm_config_comissao_vendedor_ano_mes_uniq'),
        ),
    ]
