# Generated by Django 5.2.1 on 2026-02-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0085_config_comissao_vendedor_ano_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcomissaovendedor',
            name='desconta_boleto_pap',
            field=models.BooleanField(default=True, verbose_name='Desconta Boleto PAP?'),
        ),
    ]
