# Generated by Django 5.2.1 on 2026-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0086_add_desconta_boleto_pap'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaochurn',
            name='nr_velocidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocidade/Plano (ex: 500MB, 700MB, 1GB)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_churn_aplicado_em',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Desconto Churn aplicado em (AAAAMM)'),
        ),
    ]
