# Generated by Django 5.2.1 on 2026-02-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0087_churn_nr_velocidade_e_desconto_aplicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaEsperaPAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, max_length=100)),
                ('tipo_acao', models.CharField(choices=[('vender', 'Vender'), ('pedido', 'Pedido'), ('status', 'Status'), ('credito', 'Crédito')], default='vender', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sessao_whatsapp_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fila espera PAP',
                'verbose_name_plural': 'Fila espera PAP',
                'db_table': 'crm_fila_espera_pap',
                'ordering': ['created_at'],
            },
        ),
    ]
