# Generated by Django 5.2.1 on 2026-02-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0089_papboemuso_tipo_automacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='regracomissaofaixa',
            name='finalidade',
            field=models.CharField(choices=[('COMISSAO', 'Pagamento de comissão'), ('ADIANTAMENTO', 'Adiantamento')], default='COMISSAO', help_text='Comissão = folha de pagamento (usa MIN/MAX). Adiantamento = só tela de adiantamento.', max_length=20),
        ),
    ]
