# Generated by Django 5.2.1 on 2026-02-27 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0091_backfill_finalidade_adiantamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='papconfirmacaocliente',
            name='venda',
            field=models.ForeignKey(blank=True, help_text='Preenchido quando o resumo foi enviado da auditoria; ao confirmar, gera protocolo nesta venda.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pap_confirmacoes_auditoria', to='crm_app.venda'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_confirmou_auditoria',
            field=models.BooleanField(blank=True, default=None, help_text='True se o cliente respondeu SIM/CONFIRMAR ao resumo enviado; False se BO marcou que não confirmou; null se ainda não definido.', null=True, verbose_name='Cliente confirmou resumo (auditoria)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_confirmacao_auditoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora confirmação cliente (auditoria)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='protocolo_confirmacao_auditoria',
            field=models.CharField(blank=True, db_index=True, help_text='Formato AAAAMMDDHHMM + ID da venda (ex.: 2026022621403383). Gerado quando o cliente confirma pelo WhatsApp.', max_length=30, null=True, verbose_name='Protocolo confirmação cliente (auditoria)'),
        ),
    ]
