# Generated by Django 5.2.1 on 2026-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0092_add_auditoria_retorno_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaowhatsapp',
            name='data_ultimo_aviso_nao_autorizado',
            field=models.DateField(blank=True, help_text='Quando o usuário não está autorizado a chamar no bot, usamos esta data para enviar o aviso apenas uma vez por dia.', null=True, verbose_name='Data do último aviso de usuário não autorizado'),
        ),
    ]
