# Generated by Django 5.2.1 on 2026-03-01 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0093_sessao_data_ultimo_aviso_nao_autorizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoConhecimentoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do documento', max_length=255)),
                ('arquivo', models.FileField(help_text='Arquivo (PDF, XLS/XLSX, PPT/PPTX)', upload_to='conhecimento_ia/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('PPT', 'PowerPoint'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('conteudo_extraido', models.TextField(blank=True, help_text='Texto extraído do arquivo para a IA (preenchido no processamento)')),
                ('ativo', models.BooleanField(default=True, help_text='Se inativo, não entra no contexto da IA')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_conhecimento_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Conhecimento IA',
                'verbose_name_plural': 'Documentos Conhecimento IA',
                'db_table': 'crm_documento_conhecimento_ia',
                'ordering': ['-data_upload'],
            },
        ),
    ]
