# Generated by Django 5.2.1 on 2026-03-01 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0094_documento_conhecimento_ia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlConhecimentoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL da página', max_length=2000)),
                ('titulo', models.CharField(help_text='Título ou descrição', max_length=255)),
                ('conteudo_extraido', models.TextField(blank=True, help_text='Texto extraído da página (e de links do mesmo domínio, se crawlou)')),
                ('ativo', models.BooleanField(default=True, help_text='Se inativo, não entra no contexto da IA')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls_conhecimento_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL Conhecimento IA',
                'verbose_name_plural': 'URLs Conhecimento IA',
                'db_table': 'crm_url_conhecimento_ia',
                'ordering': ['-data_upload'],
            },
        ),
    ]
