# Generated by Django 5.2.1 on 2026-03-02 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0095_url_conhecimento_ia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoEstabelecimentoCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_raiz', models.CharField(db_index=True, help_text='8 primeiros dígitos do CNPJ', max_length=8)),
                ('cnpj_ordem', models.CharField(help_text='Dígitos 9-12 do CNPJ', max_length=4)),
                ('cnpj_dv', models.CharField(help_text='Dígitos verificadores', max_length=2)),
                ('cnpj_completo', models.CharField(blank=True, db_index=True, help_text='CNPJ completo (raiz+ordem+dv)', max_length=14)),
                ('identificador_matriz_filial', models.CharField(blank=True, max_length=1)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('situacao_cadastral', models.CharField(blank=True, db_index=True, max_length=2)),
                ('data_situacao_cadastral', models.CharField(blank=True, max_length=8)),
                ('motivo_situacao_cadastral', models.CharField(blank=True, max_length=2)),
                ('nome_cidade_exterior', models.CharField(blank=True, max_length=255)),
                ('codigo_pais', models.CharField(blank=True, max_length=3)),
                ('data_inicio_atividade', models.CharField(blank=True, max_length=8)),
                ('cnae_fiscal', models.CharField(blank=True, db_index=True, max_length=7)),
                ('cnae_secundarios', models.TextField(blank=True)),
                ('tipo_logradouro', models.CharField(blank=True, max_length=50)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('uf', models.CharField(blank=True, db_index=True, max_length=2)),
                ('codigo_municipio', models.CharField(blank=True, db_index=True, max_length=7)),
                ('ddd_telefone_1', models.CharField(blank=True, max_length=3)),
                ('telefone_1', models.CharField(blank=True, max_length=20)),
                ('ddd_telefone_2', models.CharField(blank=True, max_length=3)),
                ('telefone_2', models.CharField(blank=True, max_length=20)),
                ('ddd_fax', models.CharField(blank=True, max_length=3)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('situacao_especial', models.CharField(blank=True, max_length=255)),
                ('data_situacao_especial', models.CharField(blank=True, max_length=8)),
                ('importada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estabelecimento CNPJ (Receita Federal)',
                'verbose_name_plural': 'Estabelecimentos CNPJ (Receita Federal)',
                'db_table': 'crm_importacao_estabelecimento_cnpj',
                'ordering': ['-importada_em'],
                'indexes': [models.Index(fields=['cnpj_completo'], name='crm_importa_cnpj_co_43cb4e_idx'), models.Index(fields=['cnae_fiscal', 'codigo_municipio'], name='crm_importa_cnae_fi_626747_idx'), models.Index(fields=['situacao_cadastral'], name='crm_importa_situaca_e55a73_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogImportacaoEstabelecimentoCNPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('PARCIAL', 'Parcial')], max_length=20)),
                ('tamanho_arquivo', models.BigIntegerField(blank=True, default=0, null=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.IntegerField(blank=True, null=True)),
                ('total_linhas', models.IntegerField(default=0)),
                ('total_importadas', models.IntegerField(default=0)),
                ('total_erros', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('detalhes_json', models.JSONField(blank=True, default=dict, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Importação CNPJ',
                'verbose_name_plural': 'Logs Importação CNPJ',
                'db_table': 'crm_log_importacao_estabelecimento_cnpj',
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
