# Generated by Django 5.2.1 on 2026-03-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0096_add_importacao_estabelecimento_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaoestabelecimentocnpj',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
