# Generated by Django 5.2.1 on 2026-03-03 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0097_alter_email_to_char_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='LembreteInstalacaoEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, help_text='Telefone normalizado (apenas dígitos)', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_agendamento', models.DateField()),
                ('periodo_agendamento', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde')], max_length=10)),
                ('respondido_em', models.DateTimeField(blank=True, help_text='Quando o cliente respondeu (SIM/NÃO/SUPORTE)', null=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes_instalacao_enviados', to='crm_app.venda')),
            ],
            options={
                'verbose_name': 'Lembrete instalação enviado',
                'verbose_name_plural': 'Lembretes instalação enviados',
                'db_table': 'crm_lembrete_instalacao_enviado',
                'ordering': ['-data_envio'],
            },
        ),
    ]
