# Generated by Django 5.2.1 on 2026-03-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0098_add_lembrete_instalacao_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente_confirmou_lembrete_instalacao',
            field=models.BooleanField(blank=True, default=None, help_text='True=respondeu SIM/positivo; False=respondeu Não/Suporte/outro; null=ainda não respondeu ao lembrete.', null=True, verbose_name='Cliente confirmou instalação (lembrete)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_resposta_lembrete_instalacao',
            field=models.TextField(blank=True, help_text='Texto que o cliente enviou ao responder o lembrete de instalação.', null=True, verbose_name='Resposta do cliente ao lembrete'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_resposta_lembrete_instalacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora resposta ao lembrete'),
        ),
    ]
