# Generated by Django 5.2.1 on 2026-03-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0099_add_confirmacao_lembrete_instalacao_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='boas_vindas_enviado_em',
            field=models.DateTimeField(blank=True, help_text='Quando a mensagem de boas-vindas foi enviada ao cliente.', null=True, verbose_name='Boas-vindas enviado em'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_resposta_boas_vindas',
            field=models.TextField(blank=True, help_text='Texto que o cliente enviou ao responder a mensagem de boas-vindas.', null=True, verbose_name='Resposta do cliente (boas-vindas)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_resposta_boas_vindas',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/hora resposta boas-vindas'),
        ),
        migrations.CreateModel(
            name='BoasVindasEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, help_text='Telefone normalizado (apenas dígitos)', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, help_text='Quando o cliente respondeu', null=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boas_vindas_enviados', to='crm_app.venda')),
            ],
            options={
                'verbose_name': 'Boas-vindas enviado',
                'verbose_name_plural': 'Boas-vindas enviados',
                'db_table': 'crm_boas_vindas_enviado',
                'ordering': ['-data_envio'],
            },
        ),
    ]
