# Generated by Django 5.2.1 on 2026-03-04 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0100_add_boas_vindas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleTTDiaTratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_vendedor', models.CharField(db_index=True, max_length=50)),
                ('data', models.DateField(db_index=True)),
                ('marcado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controle_tt_tratados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Controle TT dia tratado',
                'verbose_name_plural': 'Controle TT dias tratados',
                'db_table': 'crm_controle_tt_dia_tratado',
                'ordering': ['-data', 'matricula_vendedor'],
                'unique_together': {('matricula_vendedor', 'data')},
            },
        ),
    ]
