# Generated by Django 5.2.1 on 2026-03-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0101_controle_tt_dia_tratado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CepLocalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(db_index=True, help_text='CEP apenas dígitos (8)', max_length=8, unique=True)),
                ('localidade', models.CharField(help_text='Nome do município/cidade', max_length=255)),
                ('uf', models.CharField(db_index=True, help_text='Sigla UF', max_length=2)),
            ],
            options={
                'verbose_name': 'CEP Localidade',
                'verbose_name_plural': 'CEP Localidades',
                'db_table': 'crm_cep_localidade',
                'ordering': ['cep'],
            },
        ),
    ]
