# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0102_cep_localidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaoestabelecimentocnpj',
            name='nome_municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do município (preenchido por CEP ou IBGE)'),
        ),
    ]
