# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0103_importacaoestabelecimentocnpj_nome_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentodisparo',
            name='intervalo_minutos',
            field=models.PositiveIntegerField(
                default=60,
                help_text='Intervalo mínimo em minutos entre envios (ex: 60 = 1x por hora, 30 = a cada 30 min)'
            ),
        ),
    ]
