# Generated by Django 5.2.1 on 2026-03-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0104_agendamentodisparo_intervalo_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacaoestabelecimentocnpj',
            name='nome_municipio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do município'),
        ),
    ]
