# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0105_alter_importacaoestabelecimentocnpj_nome_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEnvioPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regra_nome', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('total_destinos', models.PositiveSmallIntegerField(default=0)),
                ('sucessos', models.PositiveSmallIntegerField(default=0)),
                ('falhas', models.PositiveSmallIntegerField(default=0)),
                ('detalhe', models.CharField(blank=True, max_length=500)),
                ('regra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_envio', to='crm_app.agendamentodisparo')),
            ],
            options={
                'ordering': ['-data_hora'],
                'verbose_name': 'Log de envio Performance',
                'verbose_name_plural': 'Logs de envio Performance',
            },
        ),
    ]
