# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0106_logenvoperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentodisparo',
            name='cluster_alvo',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Filtro por cluster (vazio ou TODOS = todos). Ex: CLUSTER_1, CLUSTER_2, CLUSTER_3',
                max_length=50,
            ),
        ),
    ]
