# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0107_agendamentodisparo_cluster_alvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentodisparo',
            name='hora_fim',
            field=models.PositiveSmallIntegerField(
                default=19,
                help_text='Horário máximo (0-23) para envio na frequência diária. Ex: 19 = até 19h59.',
            ),
        ),
        migrations.AddField(
            model_name='agendamentodisparo',
            name='tipo_relatorio',
            field=models.CharField(
                choices=[('HOJE', 'Hoje'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')],
                default='HOJE',
                help_text='Qual relatório enviar: Hoje, Semanal ou Mensal.',
                max_length=10,
            ),
        ),
    ]
