# Generated by Django 5.2.1 on 2026-03-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0108_agendamentodisparo_hora_fim_tipo_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlettdiatratado',
            name='tipo',
            field=models.CharField(choices=[('tratado', 'Venda registrada no dia'), ('nao_vendas', 'Não foi possível ter vendas no dia')], default='tratado', max_length=20),
        ),
    ]
