# Generated by Django 5.2.1 on 2026-03-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def popular_status_boas_vindas(apps, schema_editor):
    StatusBoasVindas = apps.get_model('crm_app', 'StatusBoasVindas')
    StatusBoasVindas.objects.bulk_create([
        StatusBoasVindas(codigo='PENDENTE', nome='Pendente', cor='#6c757d', ordem=0),
        StatusBoasVindas(codigo='OK', nome='OK (satisfeito)', cor='#198754', ordem=1),
        StatusBoasVindas(codigo='ERRO_VENDAS', nome='Erro de vendas', cor='#dc3545', ordem=2),
        StatusBoasVindas(codigo='ERRO_TECNICO', nome='Erro técnico', cor='#fd7e14', ordem=3),
        StatusBoasVindas(codigo='OUTROS', nome='Outros', cor='#6c757d', ordem=4),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0109_controle_tt_tipo_marcacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBoasVindas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(default='#6c757d', max_length=7)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'crm_status_boas_vindas',
                'verbose_name': 'Status Boas-Vindas',
                'verbose_name_plural': 'Status Boas-Vindas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MensagemClienteBoasVindas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Mensagem original do cliente')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('direcao', models.CharField(choices=[('ENTRADA', 'Cliente'), ('SAIDA', 'Sistema')], default='ENTRADA', max_length=10)),
                ('boas_vindas_enviado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='crm_app.boasvindasenviado')),
            ],
            options={
                'db_table': 'crm_mensagem_cliente_boas_vindas',
                'verbose_name': 'Mensagem Cliente (Boas-Vindas)',
                'verbose_name_plural': 'Mensagens Cliente (Boas-Vindas)',
                'ordering': ['data_hora'],
            },
        ),
        migrations.AddField(
            model_name='boasvindasenviado',
            name='status_boas_vindas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='crm_app.statusboasvindas', verbose_name='Status (BO)'),
        ),
        migrations.AddField(
            model_name='boasvindasenviado',
            name='status_definido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boas_vindas_status_definidos', to=settings.AUTH_USER_MODEL, verbose_name='Status definido por'),
        ),
        migrations.AddField(
            model_name='boasvindasenviado',
            name='status_definido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status definido em'),
        ),
        migrations.AddField(
            model_name='boasvindasenviado',
            name='sugestao_status_ia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Sugestão de status pela IA'),
        ),
        migrations.RunPython(popular_status_boas_vindas, migrations.RunPython.noop),
    ]
