# Generated by Django 5.2.1 on 2026-03-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0110_boas_vindas_gestao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaEnvioBoasVindas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_instalacao', models.DateField(help_text='Data das instalações que originaram esta fila')),
                ('agendado_para', models.DateTimeField(db_index=True, help_text='Horário previsto para envio (8h-16h)')),
                ('enviado_em', models.DateTimeField(blank=True, help_text='Quando foi enviado', null=True)),
                ('erro', models.TextField(blank=True, help_text='Mensagem de erro se falhou', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filas_boas_vindas_criadas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila_boas_vindas', to='crm_app.venda')),
            ],
            options={
                'verbose_name': 'Fila envio boas-vindas',
                'verbose_name_plural': 'Filas envio boas-vindas',
                'db_table': 'crm_fila_envio_boas_vindas',
                'ordering': ['agendado_para'],
            },
        ),
    ]
