# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0111_fila_envio_boas_vindas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='papconfirmacaocliente',
            name='enviado_por',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuário que enviou o resumo do plano pela auditoria.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='resumos_plano_enviados',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Enviado por (BO)',
            ),
        ),
    ]
