# Generated by Django 5.2.1 on 2026-03-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0112_papconfirmacaocliente_enviado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteciparinstalacaosolicitacao',
            name='observacao_reparo',
            field=models.TextField(blank=True, verbose_name='Observação no reparo (ex.: internet não funciona total ou com lentidão)'),
        ),
        migrations.AddField(
            model_name='anteciparinstalacaosolicitacao',
            name='tipo_solicitacao',
            field=models.CharField(choices=[('antecipacao', 'Antecipação'), ('reparo', 'Reparo')], default='antecipacao', max_length=20, verbose_name='Tipo (Antecipação ou Reparo)'),
        ),
    ]
