# Generated by Django 5.2.1 on 2026-03-12 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0113_antecipar_instalacao_reparo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anteciparinstalacaosolicitacao',
            name='resposta_gc',
            field=models.CharField(blank=True, choices=[('solicitado', 'Solicitado (encaminhada para Vtal)'), ('antecipada', 'Antecipada'), ('nao_antecipada', 'Não antecipada')], max_length=20, null=True, verbose_name='Resposta do GC'),
        ),
        migrations.AddField(
            model_name='anteciparinstalacaosolicitacao',
            name='resposta_gc_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da resposta GC'),
        ),
        migrations.AddField(
            model_name='anteciparinstalacaosolicitacao',
            name='resposta_gc_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_gc_antecipar', to=settings.AUTH_USER_MODEL),
        ),
    ]
