# Generated by Django 5.2.1 on 2026-03-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0114_antecipar_instalacao_resposta_gc'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_instalacao_fisica',
            field=models.DateField(blank=True, db_index=True, help_text='Data em que a instalação ocorreu de fato no cliente. Usada em performance/dashboard para consultores. Editável apenas por BackOffice/Diretoria/Admin.', null=True, verbose_name='Data instalação (no cliente)'),
        ),
    ]
