# Generated by Django 5.2.1 on 2026-03-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0118_historico_consulta_status_execucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialigacao',
            name='provedor',
            field=models.CharField(choices=[('ZENVIA', 'Zenvia Voice API'), ('SONAX', 'Sonax PABX / click2call')], default='ZENVIA', max_length=30),
        ),
    ]
