# Generated by Django 5.2.1 on 2026-03-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0119_auditoria_ligacao_provedor_sonax'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorialigacao',
            name='data_fim_chamada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditorialigacao',
            name='data_inicio_chamada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditorialigacao',
            name='id_contato',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='auditorialigacao',
            name='numero_receptivo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditorialigacao',
            name='status_atendimento',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='auditorialigacao',
            name='status_chamada_provedor',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
