# Generated by Django 5.2.1 on 2026-03-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0121_venda_antecipacao_comissao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunilVendaWppTentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, max_length=100)),
                ('matricula_pap_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('bo_usuario_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('abandonado', 'Abandonado')], db_index=True, default='em_andamento', max_length=20)),
                ('etapa_codigo_atual', models.CharField(blank=True, default='', max_length=80)),
                ('funil_estagio_max', models.CharField(blank=True, choices=[('viabilidade', 'Viabilidade'), ('cadastro', 'Cadastro'), ('contato', 'Contato'), ('credito', 'Crédito'), ('oferta', 'Oferta'), ('pedido', 'Pedido')], db_index=True, default='', max_length=20)),
                ('protocolo_pap', models.CharField(blank=True, default='', max_length=160)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('credito_resultado', models.CharField(blank=True, default='', max_length=255)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('dados_agregados', models.JSONField(blank=True, default=dict)),
                ('sessao_whatsapp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funil_tentativas', to='crm_app.sessaowhatsapp')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funil_vendas_wpp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Funil Venda WPP (tentativa)',
                'verbose_name_plural': 'Funil Vendas WPP (tentativas)',
                'db_table': 'crm_funil_venda_wpp_tentativa',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='FunilVendaWppEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('etapa_codigo', models.CharField(db_index=True, max_length=80)),
                ('funil_estagio', models.CharField(choices=[('viabilidade', 'Viabilidade'), ('cadastro', 'Cadastro'), ('contato', 'Contato'), ('credito', 'Crédito'), ('oferta', 'Oferta'), ('pedido', 'Pedido')], default='viabilidade', max_length=20)),
                ('tipo_evento', models.CharField(choices=[('input', 'Input'), ('transicao', 'Transição'), ('erro_pap', 'Erro PAP'), ('credito', 'Crédito'), ('protocolo', 'Protocolo'), ('status', 'Status')], default='input', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='crm_app.funilvendawpptentativa')),
            ],
            options={
                'verbose_name': 'Funil Venda WPP (evento)',
                'verbose_name_plural': 'Funil Vendas WPP (eventos)',
                'db_table': 'crm_funil_venda_wpp_evento',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='funilvendawpptentativa',
            index=models.Index(fields=['-iniciado_em', 'status'], name='crm_funil_v_iniciad_a65ade_idx'),
        ),
        migrations.AddIndex(
            model_name='funilvendawpptentativa',
            index=models.Index(fields=['telefone', '-iniciado_em'], name='crm_funil_v_telefon_baf89f_idx'),
        ),
    ]
