# Generated by Django 5.2.1 on 2026-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0123_venda_mes_nascimento_pap'),
    ]

    operations = [
        migrations.AddField(
            model_name='papconfirmacaocliente',
            name='protocolo_pedido',
            field=models.CharField(blank=True, db_index=True, help_text='Protocolo PAP do pedido ao enviar o resumo (evita SIM de outra venda no mesmo celular).', max_length=64, null=True),
        ),
    ]
