# Generated by Django 5.2.1 on 2026-03-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0124_pap_confirmacao_protocolo_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapSequenciaConfirmacaoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(db_index=True, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PAP sequência confirmação (dia)',
                'verbose_name_plural': 'PAP sequências confirmação (dia)',
                'db_table': 'crm_pap_sequencia_confirmacao_dia',
            },
        ),
    ]
