# Generated by Django 5.2.1 on 2026-03-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0125_pap_sequencia_confirmacao_dia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PapSequenciaConfirmacaoDia',
        ),
    ]
