# Generated by Django 5.2.1 on 2026-03-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0126_remove_pap_sequencia_confirmacao_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PapProtocoloConfirmacaoSequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janela', models.CharField(db_index=True, max_length=12, unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'PAP protocolo confirmação (sequência/min)',
                'verbose_name_plural': 'PAP protocolos confirmação (sequência/min)',
                'db_table': 'crm_pap_protocolo_confirmacao_sequencia',
            },
        ),
        migrations.AddField(
            model_name='papconfirmacaocliente',
            name='protocolo_confirmacao_envio',
            field=models.CharField(blank=True, db_index=True, help_text='Protocolo enviado ao cliente ao confirmar (YYYYMMDDHHMM + seq 4 dígitos).', max_length=24, null=True),
        ),
    ]
