# Generated by Django 5.2.1 on 2026-04-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0129_venda_adiantamento_cnpj_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='tipo',
            field=models.CharField(choices=[('ADIANTAMENTO_CNPJ', 'Adiantamento CNPJ'), ('ADIANTAMENTO_COMISSAO', 'Adiantamento de Comissão'), ('BONUS_PREMIACAO', 'Bônus/Premiação'), ('DESCONTO', 'Desconto Avulso')], max_length=30),
        ),
    ]
