# Generated by Django 5.2.1 on 2026-04-08 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0130_lancamento_bonus_premiacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoComissaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('valor_recebido_ciclo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('enviado_whatsapp_em', models.DateTimeField(blank=True, null=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='crm_app.pagamentocomissao')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_comissao_itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_pagamento_comissao_item',
                'unique_together': {('pagamento', 'vendedor')},
            },
        ),
    ]
