# Generated by Django 5.2.1 on 2026-04-12 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0132_agendamentodisparo_publico_prioridade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='adiantamento_sabado_manual',
            field=models.BooleanField(default=False, verbose_name='Adiant. sábado (marcação manual)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='adiantamento_sabado_marcado',
            field=models.BooleanField(default=False, help_text='Comissão antecipada na aba Agendados (O.S. aberta em sábado, conforme regra).', verbose_name='Adiantamento sábado marcado'),
        ),
        migrations.AddField(
            model_name='venda',
            name='adiantamento_sabado_marcado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Adiant. sábado marcado em'),
        ),
        migrations.AddField(
            model_name='venda',
            name='adiantamento_sabado_marcado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_adiantamento_sabado_marcado', to=settings.AUTH_USER_MODEL, verbose_name='Adiant. sábado marcado por'),
        ),
        migrations.AddField(
            model_name='venda',
            name='adiantamento_sabado_obs_manual',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Observação (marcação manual)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='adiantamento_sabado_quitado_em',
            field=models.DateTimeField(blank=True, help_text='Preenchido ao instalar para não gerar segundo pagamento de adiantamento.', null=True, verbose_name='Adiant. sábado quitado na instalação em'),
        ),
        migrations.AddField(
            model_name='venda',
            name='adiantamento_sabado_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor adiantamento sábado (snapshot)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='flag_desc_adiantamento_sabado',
            field=models.BooleanField(default=False, help_text='Desconto na folha (cancelamento ou estorno) já aplicado.', verbose_name='Desc. adiant. sábado processado'),
        ),
    ]
