# Generated by Django 5.2.1 on 2026-07-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0162_teams_notificacao_operacional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhatsappWebhookFila',
        ),
        migrations.RenameIndex(
            model_name='historicoatendimentoiacliente',
            new_name='crm_histori_venda_i_18e923_idx',
            old_name='crm_hist_ia_venda_idx',
        ),
        migrations.RenameIndex(
            model_name='historicoatendimentoiacliente',
            new_name='crm_histori_telefon_6969c1_idx',
            old_name='crm_hist_ia_tel_idx',
        ),
        migrations.RenameIndex(
            model_name='pendenciaclientemsgenviada',
            new_name='crm_pendenc_venda_i_c9e444_idx',
            old_name='crm_pend_cl_msg_v_m_s_idx',
        ),
        migrations.RenameIndex(
            model_name='vendaesteiraevento',
            new_name='crm_venda_e_venda_i_17f849_idx',
            old_name='crm_venda_e_venda_i_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='vendaesteiraevento',
            new_name='crm_venda_e_tipo_ev_1ae602_idx',
            old_name='crm_venda_e_tipo_ev_4c9b1e_idx',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='classificacao_mei',
            field=models.CharField(blank=True, choices=[('MEI', 'MEI'), ('NMEI', 'NMEI')], db_index=True, help_text='MEI, NMEI (não MEI), INDETERMINADO ou CPF.', max_length=20, null=True, verbose_name='Classificação MEI'),
        ),
        migrations.AlterField(
            model_name='possoreagendarconsultorsessao',
            name='datas_opcoes_json',
            field=models.CharField(blank=True, default='', help_text='JSON com 3 datas ISO oferecidas ao consultor.', max_length=128),
        ),
        migrations.AlterField(
            model_name='possoreagendarconsultorsessao',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='messageId Z-API da última mensagem com botões.', max_length=128),
        ),
        migrations.AlterField(
            model_name='recordapoia',
            name='url_externa',
            field=models.TextField(blank=True, help_text='URL de backup (R2) para sobreviver a redeploys sem volume persistente', null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='adiantamento_sabado_valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor efetivamente pago no sábado; base para complemento na folha.', max_digits=10, null=True, verbose_name='Valor pago adiantamento sábado'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='classificacao_mei',
            field=models.CharField(blank=True, choices=[('MEI', 'MEI'), ('NMEI', 'NMEI')], db_index=True, help_text='Snapshot MEI/NMEI no momento do cadastro da venda.', max_length=20, null=True, verbose_name='Classificação MEI na venda'),
        ),
    ]
