# Generated by Django 5.2.1 on 2026-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0165_restore_whatsapp_webhook_fila'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gdpprecomunicipio',
            new_name='crm_gdp_pre_municip_c9a980_idx',
            old_name='crm_gdp_pre_municip_8f0a2a_idx',
        ),
        migrations.RenameIndex(
            model_name='gdpprecomunicipio',
            new_name='crm_gdp_pre_cod_ibg_d11fbe_idx',
            old_name='crm_gdp_pre_cod_ib_5d4b1c_idx',
        ),
        migrations.RenameIndex(
            model_name='whatsappwebhookfila',
            new_name='crm_whatsap_status_3d3677_idx',
            old_name='crm_wa_wh_status_idx',
        ),
        migrations.AlterField(
            model_name='planovalorescomissao',
            name='banda_comissao',
            field=models.CharField(choices=[('500MB', '500 MB'), ('600MB', '600 MB'), ('700MB', '700 MB'), ('800MB', '800 MB'), ('1GB', '1 GB'), ('PERSONALIZADO', 'Personalizado')], default='PERSONALIZADO', max_length=20, verbose_name='Banda nas regras de faixa'),
        ),
    ]
