# Generated by Django 5.2.1 on 2026-07-14 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0167_comunicado_filtros_envio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppIaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia_contatos_externos_ativa', models.BooleanField(default=True, help_text='Responde automaticamente números sem usuário/venda cadastrados.', verbose_name='IA para contatos externos')),
                ('ia_clientes_venda_ativa', models.BooleanField(default=True, help_text='Atendimento automático com dados do pedido (boas-vindas, lembrete, etc.).', verbose_name='IA para clientes com venda')),
                ('ia_vendedores_duvidas_ativa', models.BooleanField(default=True, help_text='Responde perguntas livres de vendedores na etapa inicial.', verbose_name='IA para dúvidas de vendedores')),
                ('ia_boas_vindas_sugestao_ativa', models.BooleanField(default=True, help_text='Classifica a primeira resposta do cliente (OK/ERRO/etc.) para o backoffice.', verbose_name='IA sugere status em boas-vindas')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Config. IA WhatsApp',
                'verbose_name_plural': 'Config. IA WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTelefoneSemIa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Somente dígitos (ex.: 5511999998888 ou 11999998888).', max_length=20, unique=True, verbose_name='Telefone')),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('motivo', models.CharField(choices=[('conversa_manual', 'Conversa manual (externo)'), ('loop_ia', 'Loop de respostas IA'), ('outro', 'Outro')], default='conversa_manual', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telefones_sem_ia_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telefone sem IA (WhatsApp)',
                'verbose_name_plural': 'Telefones sem IA (WhatsApp)',
                'db_table': 'crm_whatsapp_telefone_sem_ia',
                'ordering': ['-criado_em'],
            },
        ),
    ]
