# Generated by Django 5.2.1 on 2026-07-22 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0168_whatsapp_ia_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatisticabotwhatsapp',
            name='comando',
            field=models.CharField(choices=[('FACHADA', 'Fachada'), ('DFV', 'DFV (Power BI)'), ('VIABILIDADE', 'Viabilidade'), ('FATURA', 'Fatura'), ('STATUS', 'Status'), ('CREDITO', 'Crédito')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='BrProntoBoEmUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_telefone', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('sessao_whatsapp_id', models.IntegerField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, default='', help_text='origem da reserva: bio | auditoria | etc.', max_length=30)),
                ('bo_usuario', models.ForeignKey(help_text='Usuário cujo login Br Pronto está em uso', on_delete=django.db.models.deletion.CASCADE, related_name='brpronto_sessoes_em_uso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Br Pronto BO em Uso',
                'verbose_name_plural': 'Br Pronto BOs em Uso',
                'db_table': 'crm_brpronto_bo_em_uso',
            },
        ),
    ]
