# Generated by Django 5.2.1 on 2026-07-24 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0171_venda_biometria_aprovada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandaInclusaoViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('ENVIADA', 'Enviada ao Forms'), ('ERRO', 'Erro'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDENTE', max_length=20)),
                ('telefone_solicitante', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('form_payload', models.JSONField(blank=True, default=dict)),
                ('arquivos_urls', models.JSONField(blank=True, default=list)),
                ('r2_folder', models.CharField(blank=True, default='', max_length=255)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('erro_mensagem', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_inclusao_auditadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandas_inclusao_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demanda Inclusão/Viabilidade',
                'verbose_name_plural': 'Demandas Inclusão/Viabilidade',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', '-criado_em'], name='crm_app_dem_status_e9746c_idx')],
            },
        ),
    ]
