# Generated by Django 5.2.1 on 2026-07-26 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0174_pedido_ajuda_gc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioTratamentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False, verbose_name='Relatório diário ativo')),
                ('destino_telefone', models.CharField(blank=True, default='', help_text='Telefone da diretoria (com DDD) ou ID de grupo WhatsApp (ex.: 12036...@g.us).', max_length=60, verbose_name='Destino (telefone ou ID de grupo)')),
                ('horario_envio', models.TimeField(blank=True, help_text='Horário no fim do dia para disparar o relatório (seg-sex).', null=True, verbose_name='Horário de envio (HH:MM)')),
                ('incluir_auditoria', models.BooleanField(default=True)),
                ('incluir_esteira', models.BooleanField(default=True)),
                ('limite_outlier_minutos', models.PositiveIntegerField(default=15, help_text='Sessões acima deste tempo são destacadas como fora do padrão no relatório.')),
                ('timeout_ociosidade_minutos', models.PositiveIntegerField(default=10, help_text='Sem heartbeat por este tempo, a sessão é encerrada como TIMEOUT.')),
                ('controle_disparos', models.JSONField(blank=True, default=dict)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config. relatório de tratamento',
                'verbose_name_plural': 'Config. relatório de tratamento',
                'db_table': 'crm_relatorio_tratamento_config',
            },
        ),
        migrations.CreateModel(
            name='SessaoTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('AUDITORIA', 'Auditoria'), ('ESTEIRA', 'Esteira')], db_index=True, max_length=16)),
                ('iniciado_em', models.DateTimeField(db_index=True)),
                ('ultimo_ping', models.DateTimeField()),
                ('finalizado_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('motivo_fim', models.CharField(blank=True, choices=[('APROVADO', 'Aprovado/Auditado'), ('CADASTRADO', 'Cadastrado'), ('REPROVADO', 'Reprovado/Pendenciado'), ('SALVO', 'Salvo (esteira)'), ('LIBERADO', 'Liberado sem decisão'), ('ABANDONO', 'Abandono (saiu da tela)'), ('TIMEOUT', 'Timeout (ociosidade)')], default='', max_length=16)),
                ('status_resultado', models.CharField(blank=True, default='', help_text='Nome do status aplicado ao encerrar (ex.: CADASTRADA, REPROVADA).', max_length=120)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_tratamento', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_tratamento', to='crm_app.venda')),
            ],
            options={
                'verbose_name': 'Sessão de tratamento',
                'verbose_name_plural': 'Sessões de tratamento',
                'db_table': 'crm_sessao_tratamento',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['modulo', 'iniciado_em'], name='crm_sessao__modulo_44e03e_idx'), models.Index(fields=['usuario', 'iniciado_em'], name='crm_sessao__usuario_15ea4c_idx'), models.Index(fields=['finalizado_em'], name='crm_sessao__finaliz_19dc15_idx'), models.Index(fields=['venda', 'modulo', 'finalizado_em'], name='crm_sessao__venda_i_518025_idx')],
            },
        ),
    ]
