# Generated by Django 5.2.1 on 2026-07-28 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0177_venda_pap_status_consulta_erro_e_concluido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratom10',
            name='orfao',
            field=models.BooleanField(db_index=True, default=False, help_text='Contrato criado só pelo FPD, sem venda/CPF — aguarda vínculo para tratar'),
        ),
        migrations.CreateModel(
            name='HistoricoEnvioQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail')], max_length=20)),
                ('destinatario', models.CharField(max_length=255)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('sucesso', models.BooleanField(default=True)),
                ('erro', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_envios_qualidade', to='crm_app.contratom10')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_qualidade', to=settings.AUTH_USER_MODEL)),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_envios_qualidade', to='crm_app.faturam10')),
            ],
            options={
                'verbose_name': 'Histórico de Envio Qualidade',
                'verbose_name_plural': 'Históricos de Envio Qualidade',
                'ordering': ['-criado_em'],
            },
        ),
    ]
