# Generated by Django 5.2.1 on 2026-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0178_qualidade_orfao_historico_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturam10',
            name='data_promessa_pagamento',
            field=models.DateField(blank=True, help_text='Data em que o cliente prometeu pagar (tratamento Qualidade)', null=True),
        ),
    ]
