# Generated by Django 5.2.1 on 2026-07-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0179_fatura_promessa_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratom10',
            name='status_tratamento',
            field=models.ForeignKey(blank=True, help_text='Status de tratamento do BO no módulo Qualidade (Cadastros Gerais → Status tipo Qualidade)', limit_choices_to={'tipo': 'Qualidade'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_m10_tratamento', to='crm_app.statuscrm'),
        ),
        migrations.AlterField(
            model_name='statuscrm',
            name='tipo',
            field=models.CharField(choices=[('Tratamento', 'Tratamento'), ('Esteira', 'Esteira'), ('Comissionamento', 'Comissionamento'), ('Qualidade', 'Qualidade')], max_length=50),
        ),
    ]
