# Generated by Django 5.2.1 on 2026-07-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0180_qualidade_status_tratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='assertiva_consultada',
            field=models.BooleanField(default=False, help_text='Indica se a API Assertiva respondeu à consulta cadastral.'),
        ),
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='assertiva_dados',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot normalizado dos contatos e endereço retornados pela Assertiva.'),
        ),
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='assertiva_erro',
            field=models.TextField(blank=True, default='', help_text='Erro ocorrido ao consultar ou validar os dados da Assertiva.'),
        ),
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='status_execucao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], db_index=True, default='pendente', help_text='Estado atual/final da execução da consulta.', max_length=20),
        ),
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='telefone_solicitante',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Telefone do usuário que solicitou a análise pelo WhatsApp.', max_length=20),
        ),
        migrations.AlterField(
            model_name='analisecreditohistorico',
            name='aprovado',
            field=models.BooleanField(blank=True, help_text='True se crédito aprovado, False se negado', null=True),
        ),
    ]
