# Generated by Django 5.2.1 on 2026-07-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0181_analise_credito_assertiva_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='endereco_utilizado',
            field=models.JSONField(blank=True, default=dict, help_text='Endereço usado na viabilidade (origem assertiva/padrao) e bloqueios encontrados nas tentativas anteriores.'),
        ),
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='origem_contato',
            field=models.CharField(choices=[('assertiva', 'Assertiva'), ('aleatorio', 'Aleatório'), ('misto', 'Misto')], default='assertiva', help_text='Origem do telefone/e-mail aceitos pelo PAP: dados da Assertiva, gerados aleatoriamente ou uma combinação dos dois.', max_length=20),
        ),
    ]
