# Generated by Django 5.2.1 on 2026-07-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0182_analise_credito_endereco_origem_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleTTCreditoCursorPap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bo_matricula', models.CharField(help_text='Matrícula do login BO/PDV cuja lista de vendedores é percorrida.', max_length=50, unique=True)),
                ('ultima_matricula', models.CharField(blank=True, default='', help_text='Última matrícula entregue; a próxima consulta começa depois dela.', max_length=50)),
                ('posicao', models.PositiveIntegerField(default=0, help_text='Posição da última matrícula na lista ordenada (auditoria).')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Controle TT crédito (cursor PAP)',
                'verbose_name_plural': 'Controle TT crédito (cursor PAP)',
                'db_table': 'crm_controle_tt_credito_cursor_pap',
                'ordering': ['bo_matricula'],
            },
        ),
    ]
