# Generated by Django 5.2.1 on 2026-07-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0183_controle_tt_credito_cursor_pap'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecusadoPapCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='E-mail recusado pelo PAP (sempre em minúsculas).', max_length=254, unique=True)),
                ('motivo', models.CharField(choices=[('EMAIL_INVALIDO', 'E-mail inválido para o Nio'), ('EMAIL_REJEITADO', 'E-mail já usado em pedido anterior')], db_index=True, default='EMAIL_INVALIDO', help_text='Classificação do modal Atenção! que recusou o e-mail.', max_length=20)),
                ('ocorrencias', models.PositiveIntegerField(default=1, help_text='Quantidade de vezes que o PAP recusou este e-mail.')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-mail recusado no PAP (crédito)',
                'verbose_name_plural': 'E-mails recusados no PAP (crédito)',
                'db_table': 'crm_email_recusado_pap_credito',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
