# Generated by Django 5.2.1 on 2026-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0184_email_recusado_pap_credito'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='contato_utilizado',
            field=models.JSONField(blank=True, default=dict, help_text='Telefone(s) e e-mail aceitos pelo PAP, com a origem de cada um (assertiva ou aleatorio).'),
        ),
    ]
