# Generated by Django 5.2.1 on 2026-07-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0185_analise_credito_contato_utilizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='formas_pagamento',
            field=models.CharField(blank=True, choices=[('todas', 'Todas as formas de pagamento'), ('cartao', 'Apenas cartão de crédito')], db_index=True, default='', help_text='Quando aprovado: se o PAP liberou todas as formas de pagamento ou apenas cartão de crédito.', max_length=20),
        ),
        migrations.AddField(
            model_name='analisecreditohistorico',
            name='motivo_negativa',
            field=models.CharField(blank=True, default='', help_text='Quando negado: motivo exibido no modal de resultado do PAP.', max_length=300),
        ),
    ]
