# Generated by Django 5.2.1 on 2026-08-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0189_fatura_conferencia_fpd_tratamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCustoWhatsAppOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(db_index=True, max_length=30)),
                ('tipo_envio', models.CharField(db_index=True, max_length=20)),
                ('template_name', models.CharField(blank=True, default='', max_length=120)),
                ('categoria', models.CharField(db_index=True, max_length=30)),
                ('custo_estimado_brl', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('sucesso', models.BooleanField(db_index=True, default=True)),
                ('message_id', models.CharField(blank=True, default='', max_length=120)),
                ('origem', models.CharField(blank=True, default='', max_length=60)),
                ('erro', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Histórico custo WhatsApp oficial',
                'verbose_name_plural': 'Históricos custo WhatsApp oficial',
                'db_table': 'crm_historico_custo_whatsapp_oficial',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTarifaOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_brl', models.DecimalField(decimal_places=4, default=0.035, max_digits=10)),
                ('marketing_brl', models.DecimalField(decimal_places=4, default=0.3217, max_digits=10)),
                ('authentication_brl', models.DecimalField(decimal_places=4, default=0.035, max_digits=10)),
                ('service_brl', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('observacao', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa WhatsApp oficial',
                'verbose_name_plural': 'Tarifas WhatsApp oficial',
                'db_table': 'crm_whatsapp_tarifa_oficial',
            },
        ),
        migrations.AddIndex(
            model_name='historicocustowhatsappoficial',
            index=models.Index(fields=['criado_em', 'sucesso'], name='crm_histori_criado__068e83_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocustowhatsappoficial',
            index=models.Index(fields=['categoria', 'criado_em'], name='crm_histori_categor_7f4f1c_idx'),
        ),
    ]
