# Generated by Django 5.2.1 on 2026-08-08 03:06

from decimal import Decimal

from django.db import migrations, models


def popular_cidades_e_planos_600(apps, schema_editor):
    """Semear lista de oferta especial e habilitar R$105 nos planos 600Mb."""
    from django.db.models import Q

    from crm_app.cidades_oferta_especial_data import (
        CIDADES_OFERTA_ESPECIAL,
        VALOR_COMISSAO_600MB_CIDADE_ESPECIAL,
    )
    from crm_app.services.gdp_preco_service import normalizar_municipio

    CidadeOfertaEspecial = apps.get_model('crm_app', 'CidadeOfertaEspecial')
    Plano = apps.get_model('crm_app', 'Plano')
    PlanoValoresComissao = apps.get_model('crm_app', 'PlanoValoresComissao')

    for uf, municipio in CIDADES_OFERTA_ESPECIAL:
        uf_n = (uf or '').strip().upper()[:2]
        mun = (municipio or '').strip()
        if not uf_n or not mun:
            continue
        mun_norm = normalizar_municipio(mun)
        grafia = mun.title() if mun.isupper() else mun
        CidadeOfertaEspecial.objects.update_or_create(
            uf=uf_n,
            municipio_normalizado=mun_norm,
            defaults={'municipio': grafia, 'ativo': True},
        )

    valor = Decimal(VALOR_COMISSAO_600MB_CIDADE_ESPECIAL)
    planos_600 = Plano.objects.filter(ativo=True).filter(
        Q(gdp_velocidade_mbps=600)
        | Q(nome__icontains='600MB')
        | Q(nome__icontains='600 MB'),
    )
    for plano in planos_600:
        vc, _ = PlanoValoresComissao.objects.get_or_create(plano=plano)
        vc.usa_comissao_cidade_especial = True
        vc.valor_pap_cidade_especial = valor
        vc.valor_cnpj_cidade_especial = valor
        vc.save(
            update_fields=[
                'usa_comissao_cidade_especial',
                'valor_pap_cidade_especial',
                'valor_cnpj_cidade_especial',
            ],
        )


def noop_reverse(apps, schema_editor):
    """Mantém dados no reverse; remoção manual se necessário."""
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0195_importacaofpd_nm_seg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CidadeOfertaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, max_length=2)),
                ('municipio', models.CharField(max_length=120)),
                ('municipio_normalizado', models.CharField(db_index=True, max_length=120)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cidade de oferta especial',
                'verbose_name_plural': 'Cidades de oferta especial',
                'db_table': 'crm_cidade_oferta_especial',
                'ordering': ['uf', 'municipio'],
            },
        ),
        migrations.AddField(
            model_name='planovalorescomissao',
            name='usa_comissao_cidade_especial',
            field=models.BooleanField(
                default=False,
                help_text=(
                    'Quando ativo, vendas deste plano em municípios da lista de oferta especial '
                    'usam valor fixo (não escala por faixa de volume).'
                ),
                verbose_name='Comissão especial em cidade de oferta',
            ),
        ),
        migrations.AddField(
            model_name='planovalorescomissao',
            name='valor_cnpj_cidade_especial',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Comissão CNPJ em cidade especial',
            ),
        ),
        migrations.AddField(
            model_name='planovalorescomissao',
            name='valor_pap_cidade_especial',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name='Comissão PAP em cidade especial',
            ),
        ),
        migrations.AddIndex(
            model_name='cidadeofertaespecial',
            index=models.Index(
                fields=['municipio_normalizado', 'uf', 'ativo'],
                name='crm_cidade__municip_510e62_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='cidadeofertaespecial',
            constraint=models.UniqueConstraint(
                fields=('uf', 'municipio_normalizado'),
                name='uniq_cidade_oferta_especial_uf_municipio',
            ),
        ),
        migrations.RunPython(popular_cidades_e_planos_600, noop_reverse),
    ]
