# Generated by Django 5.2.1 on 2026-08-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0196_cidade_oferta_especial_comissao'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historicoenvioqualidade',
            new_name='crm_app_his_contrat_1faad0_idx',
            old_name='crm_app_his_contrat_canal_idx',
        ),
        migrations.RenameIndex(
            model_name='historicoenvioqualidade',
            new_name='crm_app_his_criado__7246ad_idx',
            old_name='crm_app_his_criado_canal_idx',
        ),
        migrations.RenameIndex(
            model_name='importacaofpd',
            new_name='crm_app_imp_indicad_97947d_idx',
            old_name='crm_app_imp_indicad_sit_idx',
        ),
        migrations.RenameIndex(
            model_name='importacaofpd',
            new_name='crm_app_imp_match_s_8e0e12_idx',
            old_name='crm_app_imp_match_ind_idx',
        ),
        migrations.RenameIndex(
            model_name='importacaofpd',
            new_name='crm_app_imp_nr_orde_9baaab_idx',
            old_name='crm_app_imp_ordem_ind_idx',
        ),
    ]
