# Generated by Django 5.2.1 on 2026-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0209_alter_comunicado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='codigo_sa_ba',
            field=models.CharField(blank=True, db_index=True, help_text='Código identificador do contrato na Operadora (ex: SA-41538304, BA-...).', max_length=50, null=True, verbose_name='Código SA/BA'),
        ),
    ]
