# Generated by Django 5.2.1 on 2026-10-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0210_venda_codigo_sa_ba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappintegracaoconfig',
            name='provider',
            field=models.CharField(choices=[('zapi', 'Z-API (legado / plano B)'), ('evolution', 'Evolution + n8n (Opção B)'), ('whatsatende', 'WhatsAtende (A+B)'), ('hybrid', 'Híbrido: Z-API (equipe) + WhatsAtende oficial (cliente)'), ('meta', 'Cloud API Meta direta (cliente)')], default='zapi', max_length=20, verbose_name='Provedor ativo'),
        ),
    ]
