# Generated by Django 5.2.1 on 2026-10-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0211_whatsapp_provider_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='franquia_movel_gb',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Franquia por chip (GB)'),
        ),
        migrations.AddField(
            model_name='plano',
            name='portfolio',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador do portfólio comercial (ex.: MVNO_2026).', max_length=40, verbose_name='Portfólio'),
        ),
        migrations.AddField(
            model_name='plano',
            name='qtd_chips_moveis',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Chips móveis inclusos'),
        ),
        migrations.AddField(
            model_name='plano',
            name='segmento',
            field=models.CharField(choices=[('B2C', 'Residencial (B2C)'), ('B2B', 'Empresarial (B2B)')], default='B2C', max_length=3, verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='plano',
            name='valor_cartao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço no cartão de crédito. Se vazio, aplica o desconto padrão por velocidade.', max_digits=10, null=True, verbose_name='Valor mensal no cartão'),
        ),
    ]
