# Generated by GitHub Copilot on 2026-01-11
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0066_create_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='reemissao',
            field=models.BooleanField(default=False, verbose_name='Reemissão'),
        ),
    ]
