# Generated by Django 5.2.1 on 2025-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(blank=True, max_length=255, null=True)),
                ('filial', models.CharField(blank=True, max_length=255, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('dt_ref', models.DateField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
                ('segmento', models.CharField(blank=True, max_length=255, null=True)),
                ('localidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estacao', models.CharField(blank=True, max_length=255, null=True)),
                ('id_bundle', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('velocidade', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula_vendedor', models.CharField(blank=True, max_length=100, null=True)),
                ('classe_produto', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_canal', models.CharField(blank=True, max_length=255, null=True)),
                ('pdv_sap', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_abertura', models.DateTimeField(blank=True, null=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=100, null=True)),
                ('cluster', models.CharField(blank=True, max_length=255, null=True)),
                ('safra', models.CharField(blank=True, max_length=100, null=True)),
                ('data_agendamento', models.DateTimeField(blank=True, null=True)),
                ('dacc_sol', models.CharField(blank=True, max_length=255, null=True)),
                ('dacc_efe', models.CharField(blank=True, max_length=255, null=True)),
                ('dia_vencimento', models.IntegerField(blank=True, null=True)),
                ('duplicidade_vl_vl_mesmo_endereco_cpf_diferente', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicidade_vl_vl_mesmo_endereco_cpf_igual', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicidade_vl_planta_mesmo_endereco_cpf_igual', models.CharField(blank=True, max_length=100, null=True)),
                ('duplicidade_vl_planta_mesmo_endereco_cpf_diferente', models.CharField(blank=True, max_length=100, null=True)),
                ('contato1', models.CharField(blank=True, max_length=20, null=True)),
                ('contato2', models.CharField(blank=True, max_length=20, null=True)),
                ('contato3', models.CharField(blank=True, max_length=20, null=True)),
                ('flg_mig_cobre_fixo', models.CharField(blank=True, max_length=50, null=True)),
                ('flg_mig_cobre_velox', models.CharField(blank=True, max_length=50, null=True)),
                ('flg_mig_tv', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_pendencia', models.TextField(blank=True, null=True)),
                ('tipo_pendencia', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_pendencia', models.CharField(blank=True, max_length=100, null=True)),
                ('oferta', models.CharField(blank=True, max_length=255, null=True)),
                ('comunidade', models.CharField(blank=True, max_length=255, null=True)),
                ('gv', models.CharField(blank=True, max_length=100, null=True)),
                ('gc', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_principal_fim', models.CharField(blank=True, max_length=255, null=True)),
                ('gestao', models.CharField(blank=True, max_length=255, null=True)),
                ('st_regional', models.CharField(blank=True, max_length=255, null=True)),
                ('meio_pagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('flag_vll', models.CharField(blank=True, max_length=50, null=True)),
                ('status_checkout', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_ba', models.CharField(blank=True, max_length=100, null=True)),
                ('venda_no_app', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Registro OSAB',
                'verbose_name_plural': 'Registros OSAB',
            },
        ),
    ]
