# Generated by Django 5.2.1 on 2025-09-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='canal',
            field=models.CharField(blank=True, choices=[('PAP', 'PAP'), ('TELAG', 'TELAG'), ('TIPO', 'TIPO')], default='PAP', max_length=10, null=True),
        ),
    ]
