# Generated by Django 5.2.1 on 2025-09-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='participa_controle_presenca',
            field=models.BooleanField(default=True, help_text='Marque se este usuário deve aparecer na tela de controle de presença.', verbose_name='Participa do Controle de Presença?'),
        ),
    ]
