# Generated by Django 5.2.1 on 2025-11-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_participa_controle_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tel_whatsapp',
            field=models.CharField(blank=True, help_text='Número com DDD (apenas números). O sistema verificará se possui WhatsApp.', max_length=20, null=True, verbose_name='WhatsApp do Consultor'),
        ),
    ]
