# Generated by Django 5.2.1 on 2025-11-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_tel_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='obriga_troca_senha',
            field=models.BooleanField(default=True, help_text='Se marcado, o usuário deverá trocar a senha no próximo login.', verbose_name='Obrigar troca de senha?'),
        ),
    ]
