# Generated by Django 5.2.1 on 2025-11-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_obriga_troca_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='obriga_troca_senha',
            field=models.BooleanField(default=False, help_text='Se marcado, o usuário deverá trocar a senha no próximo login.', verbose_name='Obrigar troca de senha?'),
        ),
    ]
