# Generated by Django 5.2.1 on 2025-12-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_obriga_troca_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='canal',
            field=models.CharField(blank=True, choices=[('PAP', 'PAP'), ('DIGITAL', 'Digital'), ('RECEPTIVO', 'Receptivo'), ('PARCEIRO', 'Parceiro'), ('TELAG', 'TelAg'), ('INTERNO', 'Interno')], default='PAP', max_length=20, null=True, verbose_name='Canal de Venda'),
        ),
    ]
