# Generated by Django 5.2.1 on 2026-01-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_perfil_options_alter_usuario_canal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cluster',
            field=models.CharField(blank=True, choices=[('CLUSTER_1', 'CLUSTER 1'), ('CLUSTER_2', 'CLUSTER 2'), ('CLUSTER_3', 'CLUSTER 3')], max_length=20, null=True, verbose_name='Cluster'),
        ),
    ]
