# Generated by Django 5.2.1 on 2026-01-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='desconto_instalacao_antecipada',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
