# Generated by Django 5.2.1 on 2026-01-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_usuario_desconto_instalacao_antecipada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='desconto_instalacao_antecipada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
