# Generated by Django 5.2.1 on 2026-01-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_usuario_desconto_instalacao_antecipada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cod_perfil',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código do Perfil'),
        ),
    ]
