# Generated by Django 5.2.1 on 2026-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_perfil_cod_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cod_perfil',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código do Perfil'),
        ),
    ]
