# Generated by Django 5.2.1 on 2026-01-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_perfil_cod_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula_pap',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula PAP'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha_pap',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha PAP'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_whatsapp',
            field=models.CharField(blank=True, help_text='Número com DDD (apenas números). O sistema verificará se possui WhatsApp via validação assíncrona.', max_length=20, null=True, verbose_name='WhatsApp do Consultor'),
        ),
    ]
