# Generated by Django 5.2.1 on 2026-01-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuario_matricula_pap_usuario_senha_pap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizar_venda_sem_auditoria',
            field=models.BooleanField(default=False, help_text='Se marcado, o vendedor pode realizar vendas pelo WhatsApp usando automação do PAP.', verbose_name='Autorizar venda sem auditoria?'),
        ),
    ]
