# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_add_autorizar_venda_sem_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizar_venda_automatica',
            field=models.BooleanField(default=False, help_text='Se marcado, o vendedor poderá informar se a O.S. foi gerada automaticamente ao cadastrar vendas.', verbose_name='Autorizar venda Automática'),
        ),
    ]
