# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_add_autorizar_venda_automatica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tel_whatsapp',
            field=models.CharField(blank=True, help_text='Número com DDD (apenas números). Qualquer um dos 3 números pode interagir com o bot.', max_length=20, null=True, verbose_name='WhatsApp 1'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tel_whatsapp_2',
            field=models.CharField(blank=True, help_text='Segundo número (opcional). Pode interagir com o bot se o usuário estiver ativo.', max_length=20, null=True, verbose_name='WhatsApp 2'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tel_whatsapp_3',
            field=models.CharField(blank=True, help_text='Terceiro número (opcional). Pode interagir com o bot se o usuário estiver ativo.', max_length=20, null=True, verbose_name='WhatsApp 3'),
        ),
    ]
