# Generated by Django 5.2.1 on 2026-02-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_add_tel_whatsapp_2_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tel_whatsapp',
            field=models.CharField(blank=True, help_text='Número principal com DDD (apenas números). Notificações do sistema são enviadas só para este número. Qualquer um dos 3 pode interagir com o bot.', max_length=20, null=True, verbose_name='WhatsApp 1'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_whatsapp_2',
            field=models.CharField(blank=True, help_text='Segundo número (opcional). Só para interagir com o bot; envios do sistema vão apenas para WhatsApp 1.', max_length=20, null=True, verbose_name='WhatsApp 2'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_whatsapp_3',
            field=models.CharField(blank=True, help_text='Terceiro número (opcional). Só para interagir com o bot; envios do sistema vão apenas para WhatsApp 1.', max_length=20, null=True, verbose_name='WhatsApp 3'),
        ),
    ]
