# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_usuario_tel_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizar_analise_credito_wpp',
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, o usuário pode consultar análise de crédito pelo WhatsApp (palavra-chave CRÉDITO).",
                verbose_name='Autorizar fazer análise de crédito pelo Wpp'
            ),
        ),
    ]
