# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_add_autorizar_analise_credito_wpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='login_pap_disponivel_para_automacao',
            field=models.BooleanField(
                default=True,
                help_text='Se desmarcado, o bot/automação do WhatsApp não usará este login no pool. Use quando o BO estiver atuando no PAP para não disputar o mesmo login.',
                verbose_name='Disponibilizar login PAP para o bot (WhatsApp)'
            ),
        ),
    ]
