# Generated by Django 5.2.1 on 2026-02-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_usuario_login_pap_disponivel_para_automacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pode_gestao_acessos',
            field=models.BooleanField(default=False, help_text="Se marcado, o usuário verá o card 'Gestão de Acessos' na área interna e poderá gerenciar usuários (exceto perfis Admin e Diretoria).", verbose_name='Pode usar a ferramenta Gestão de Acessos?'),
        ),
    ]
