# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_add_pode_gestao_acessos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizar_inclusao_wpp',
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, o usuário pode usar o comando INCLUSÃO pelo WhatsApp (solicitar viabilidade via formulário).",
                verbose_name='Autorizar Inclusão/Viabilidade pelo Wpp'
            ),
        ),
    ]
