# Generated by Django 5.2.1 on 2026-02-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_pap_automacao_por_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizado_chamar_no_bot',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o usuário continua recebendo mensagens do bot, mas ao interagir receberá aviso (uma vez por dia) de que não está liberado para acesso; no mesmo dia, interações adicionais não recebem resposta.', verbose_name='Autorizado chamar no bot'),
        ),
    ]
