# Generated by Django 5.2.1 on 2026-03-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_autorizado_chamar_no_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='brpronto_dominio',
            field=models.CharField(blank=True, help_text='Domínio no login do Br Pronto (se aplicável).', max_length=100, null=True, verbose_name='Domínio Br Pronto PDV'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='brpronto_login',
            field=models.CharField(blank=True, help_text='Login para consulta de biometria no site Br Pronto (ged360). Usado na ferramenta de auditoria.', max_length=100, null=True, verbose_name='Login Br Pronto PDV'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='brpronto_senha',
            field=models.CharField(blank=True, help_text='Senha do Br Pronto. Cada backoffice/vendedor tem o seu.', max_length=128, null=True, verbose_name='Senha Br Pronto PDV'),
        ),
    ]
