# Generated by Django 5.2.1 on 2026-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_add_brpronto_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='valor_ajuda_custo_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Valor fixo mensal de ajuda de custo (ex.: parceiros). Diferente de almoço+passagem.', max_digits=10, verbose_name='Ajuda de custo mensal fixa (R$)'),
        ),
    ]
