# Generated by Django 5.2.1 on 2026-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_usuario_recebe_adiantamento_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recebe_adiantamento_sabado',
            field=models.BooleanField(default=False, help_text='Se marcado, a venda pode ser lançada como adiantada na esteira (aba Agendados) conforme Regras por Faixa (Finalidade Adiantamento).', verbose_name='Recebe adiantamento de comissão (vendas O.S. aberta em sábado)?'),
        ),
    ]
