# Generated by Django 5.2.1 on 2026-07-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_adiantamento_sabado_esteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizar_consulta_bio_wpp',
            field=models.BooleanField(default=False, help_text='Se marcado, o usuário pode usar o comando BIO no WhatsApp.', verbose_name='Autorizar consulta Bio pelo Wpp'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='brpronto_disponivel_para_automacao',
            field=models.BooleanField(default=False, help_text='Se marcado, este login entra no pool de consulta de biometria (auditoria Checar biometria e comando BIO no WhatsApp).', verbose_name='Disponibilizar login Br Pronto para o bot'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='brpronto_dominio',
            field=models.CharField(blank=True, help_text='Domínio no login do Br Pronto (ex.: BrPronto).', max_length=100, null=True, verbose_name='Domínio Br Pronto PDV'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='brpronto_login',
            field=models.CharField(blank=True, help_text='Login (matrícula TT) para consulta de biometria no ged360. Preferir perfil NIVEL2_BOPAP.', max_length=100, null=True, verbose_name='Login Br Pronto PDV'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='brpronto_senha',
            field=models.CharField(blank=True, help_text='Senha do Br Pronto. Gerenciada na Governança; usada pelo pool da automação.', max_length=128, null=True, verbose_name='Senha Br Pronto PDV'),
        ),
    ]
