# Generated by Django 5.2.1 on 2026-09-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_usuario_pode_importar_nio_terceiros'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialRoboPAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(choices=[('CONSULTA_ESTEIRA', 'Consulta PAP (Esteira)'), ('WHATSAPP_BOT', 'Bot do WhatsApp (Crédito, OS, etc)'), ('HISTORICO_VENDAS', 'Auditoria/Histórico (Excel PAP)'), ('OUTROS', 'Outros')], max_length=50, verbose_name='Função')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matrícula PAP')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha PAP')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('em_uso', models.BooleanField(default=False, verbose_name='Em Uso (Trancado)')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conta de Serviço PAP',
                'verbose_name_plural': 'Contas de Serviço PAP',
            },
        ),
    ]
