# Generated by Django 5.2.1 on 2026-09-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0209_alter_comunicado_options_and_more'),
        ('usuarios', '0033_credencialrobopap'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='operadoras_permitidas',
            field=models.ManyToManyField(blank=True, help_text='Operadoras cujos registros o usuário pode consultar e cadastrar. Sem seleção, o usuário pode acessar todas as operadoras.', related_name='usuarios_com_acesso', to='crm_app.operadora', verbose_name='Operadoras permitidas'),
        ),
    ]
