# Generated by Django 5.2.4 on 2025-08-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNaoUtil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dias_nao_uteis',
            },
        ),
        migrations.CreateModel(
            name='MotivoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255, unique=True)),
                ('gera_desconto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'motivos_ausencia',
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'registros_presenca',
            },
        ),
    ]
