# Generated by Django 5.2.4 on 2025-08-24 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presenca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='colaborador',
            field=models.ForeignKey(db_column='vendedor_id', on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presenca',
            name='lancado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_lancadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presenca',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='presenca.motivoausencia'),
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('colaborador', 'data')},
        ),
    ]
