# Generated by Django 5.2.1 on 2026-01-07 02:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0004_presenca_criado_em_presenca_editado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='presenca',
            index=models.Index(fields=['colaborador', 'data'], name='presenca_pr_colabor_f3e223_idx'),
        ),
    ]
