# Generated by Django 5.2.1 on 2026-02-12 19:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0006_confirmacao_presenca_dia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='confirmacaopresencadia',
            name='presenca_confirmacaopresencadia_data_supervisor_uniq',
        ),
        migrations.AlterUniqueTogether(
            name='confirmacaopresencadia',
            unique_together={('data', 'supervisor')},
        ),
    ]
