from django.db import models

class Osab(models.Model):
    produto = models.CharField(max_length=255, null=True, blank=True)
    filial = models.CharField(max_length=255, null=True, blank=True)
    uf = models.CharField(max_length=2, null=True, blank=True)
    dt_ref = models.DateField(null=True, blank=True)
    documento = models.CharField(max_length=255, null=True, blank=True)
    segmento = models.CharField(max_length=255, null=True, blank=True)
    localidade = models.CharField(max_length=255, null=True, blank=True)
    estacao = models.CharField(max_length=255, null=True, blank=True)
    id_bundle = models.CharField(max_length=255, null=True, blank=True)
    telefone = models.CharField(max_length=20, null=True, blank=True)
    cliente = models.CharField(max_length=255, null=True, blank=True)
    velocidade = models.CharField(max_length=100, null=True, blank=True)
    matricula_vendedor = models.CharField(max_length=100, null=True, blank=True)
    classe_produto = models.CharField(max_length=255, null=True, blank=True)
    nome_canal = models.CharField(max_length=255, null=True, blank=True)
    pdv_sap = models.CharField(max_length=255, null=True, blank=True)
    descricao = models.TextField(null=True, blank=True)
    data_abertura = models.DateTimeField(null=True, blank=True)
    data_fechamento = models.DateTimeField(null=True, blank=True)
    situacao = models.CharField(max_length=100, null=True, blank=True)
    cluster = models.CharField(max_length=255, null=True, blank=True)
    safra = models.CharField(max_length=100, null=True, blank=True)
    data_agendamento = models.DateTimeField(null=True, blank=True)
    dacc_sol = models.CharField(max_length=255, null=True, blank=True)
    dacc_efe = models.CharField(max_length=255, null=True, blank=True)
    dia_vencimento = models.IntegerField(null=True, blank=True)
    duplicidade_vl_vl_mesmo_endereco_cpf_diferente = models.CharField(max_length=100, null=True, blank=True)
    duplicidade_vl_vl_mesmo_endereco_cpf_igual = models.CharField(max_length=100, null=True, blank=True)
    duplicidade_vl_planta_mesmo_endereco_cpf_igual = models.CharField(max_length=100, null=True, blank=True)
    duplicidade_vl_planta_mesmo_endereco_cpf_diferente = models.CharField(max_length=100, null=True, blank=True)
    contato1 = models.CharField(max_length=20, null=True, blank=True)
    contato2 = models.CharField(max_length=20, null=True, blank=True)
    contato3 = models.CharField(max_length=20, null=True, blank=True)
    flg_mig_cobre_fixo = models.CharField(max_length=50, null=True, blank=True)
    flg_mig_cobre_velox = models.CharField(max_length=50, null=True, blank=True)
    flg_mig_tv = models.CharField(max_length=50, null=True, blank=True)
    desc_pendencia = models.TextField(null=True, blank=True)
    tipo_pendencia = models.CharField(max_length=255, null=True, blank=True)
    cod_pendencia = models.CharField(max_length=100, null=True, blank=True)
    oferta = models.CharField(max_length=255, null=True, blank=True)
    comunidade = models.CharField(max_length=255, null=True, blank=True)
    gv = models.CharField(max_length=100, null=True, blank=True)
    gc = models.CharField(max_length=100, null=True, blank=True)
    sap_principal_fim = models.CharField(max_length=255, null=True, blank=True)
    gestao = models.CharField(max_length=255, null=True, blank=True)
    st_regional = models.CharField(max_length=255, null=True, blank=True)
    meio_pagamento = models.CharField(max_length=100, null=True, blank=True)
    flag_vll = models.CharField(max_length=50, null=True, blank=True)
    status_checkout = models.CharField(max_length=100, null=True, blank=True)
    numero_ba = models.CharField(max_length=100, null=True, blank=True)
    venda_no_app = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = "Registro OSAB"
        verbose_name_plural = "Registros OSAB"

    def __str__(self):
        return f"{self.cliente} - {self.documento}"